import { describe, expect, it } from 'vitest';
import { MAX_COMPILE_RISK_LIST_ITEMS } from '@eforge-build/client';
import {
  buildCompilePromptSourceBundle,
  estimateCompilePreflightRisk,
  formatCompilePreflightPromptAppend,
  MODERATE_SOURCE_BYTES,
} from '@eforge-build/engine/compile-resilience/preflight';

const sentinel = 'RAW_GENERATED_SENTINEL_12345';

function smallPrd(): string {
  return ['# Small PRD', '', '## Acceptance Criteria', '', '- First criterion passes.', '- Second criterion passes.'].join('\n');
}

function generatedInventory(path = 'inventory/generated.json'): string {
  const rows = Array.from({ length: 220 }, (_, i) => `  { "path": "packages/engine/src/file-${i}.ts", "label": "${i === 177 ? sentinel : `item-${i}`}" }`).join(',\n');
  return ['# PRD', '', '## Generated Inventory', '', `\`\`\`json ${path}`, '[', rows, ']', '\`\`\`', '', '## Acceptance Criteria', '', '- The plan is generated.'].join('\n');
}

function acPrd(count: number): string {
  return ['# Many AC', '', '## Acceptance Criteria', '', ...Array.from({ length: count }, (_, i) => `- Criterion ${i + 1} exits 0.`)].join('\n');
}

describe('compile preflight compaction and risk', () => {
  it('leaves small PRDs unchanged and normal', () => {
    const source = smallPrd();
    const bundle = buildCompilePromptSourceBundle(source);
    const risk = estimateCompilePreflightRisk(bundle);
    expect(bundle.promptSource).toBe(source);
    expect(risk.acceptanceCriteriaCount).toBe(2);
    expect(risk.level).toBe('normal');
    expect(risk.recommendation.action).toBe('none');
    expect(formatCompilePreflightPromptAppend({ risk, bundle })).toBeUndefined();
  });

  it('scores oversized ordinary prose without compaction', () => {
    const source = `# Large Ordinary\n\n${'Human-authored prose. '.repeat(Math.ceil(MODERATE_SOURCE_BYTES / 20) + 50)}`;
    const bundle = buildCompilePromptSourceBundle(source);
    const risk = estimateCompilePreflightRisk(bundle);
    expect(bundle.compactions).toHaveLength(0);
    expect(risk.sourceBytes).toBe(Buffer.byteLength(source, 'utf8'));
    expect(risk.reasons).toContain('source-bytes:moderate');
  });

  it('treats 71 acceptance criteria as overflow risk', () => {
    const bundle = buildCompilePromptSourceBundle(acPrd(71));
    const risk = estimateCompilePreflightRisk(bundle, { requestedPipelineScope: 'excursion' });
    expect(risk.acceptanceCriteriaCount).toBe(71);
    expect(risk.level).toBe('overflow-risk');
    expect(risk.recommendation.action).not.toBe('none');
  });

  it('compacts embedded generated inventory and records bounded evidence', () => {
    const bundle = buildCompilePromptSourceBundle(generatedInventory());
    const risk = estimateCompilePreflightRisk(bundle);
    expect(bundle.compactions[0]).toMatchObject({ kind: 'generated-inventory' });
    expect(bundle.compactions[0].originalBytes).toBeGreaterThan(0);
    expect(bundle.compactions[0].contentHash).toMatch(/^[a-f0-9]{64}$/);
    expect(bundle.compactions[0].preservedSummary.length).toBeGreaterThan(0);
    expect(bundle.promptSource).toContain('eforge compile preflight compaction');
    expect(bundle.promptSource).not.toContain(sentinel);
    expect(risk.generatedInventory.detected).toBe(true);
    expect(risk.generatedInventory.blockCount).toBe(1);
    expect(risk.generatedInventory.omittedBytes).toBeGreaterThan(0);
    expect(risk.generatedInventory.contentHashes.length).toBeLessThanOrEqual(MAX_COMPILE_RISK_LIST_ITEMS);
    expect(risk.generatedInventory.headings).toContain('Generated Inventory');
  });

  it('preserves detected metadata when bundles are cloned', () => {
    const bundle = buildCompilePromptSourceBundle(generatedInventory());
    const risk = estimateCompilePreflightRisk({ ...bundle });
    expect(risk.generatedInventory.detected).toBe(true);
    expect(risk.generatedInventory.blockCount).toBe(1);
  });

  it('scores acceptance criteria and subsystem breadth from full stripped source', () => {
    const source = [
      '# PRD',
      '',
      '## Acceptance Criteria',
      '',
      'Generated by eforge. Do not edit.',
      ...Array.from({ length: 71 }, (_, i) => `- Criterion ${i + 1} exits 0 for packages/engine packages/client packages/monitor packages/console-ui.`),
      sentinel,
    ].join('\n');
    const bundle = buildCompilePromptSourceBundle(source);
    expect(bundle.promptSource).not.toContain(sentinel);
    const risk = estimateCompilePreflightRisk(bundle, { requestedPipelineScope: 'excursion' });
    expect(risk.acceptanceCriteriaCount).toBeGreaterThan(70);
    expect(risk.subsystemBreadth.count).toBeGreaterThanOrEqual(4);
    expect(risk.level).toBe('overflow-risk');
  });

  it('counts unique machine-readable sidecar paths and bounds path references', () => {
    const fences = Array.from({ length: MAX_COMPILE_RISK_LIST_ITEMS + 4 }, (_, i) => [
      `## Sidecar ${i}`,
      '',
      `\`\`\`json sidecars/file-${i}.json`,
      JSON.stringify(Array.from({ length: 120 }, (_unused, n) => ({ id: n, path: `sidecars/file-${i}.json` }))),
      '\`\`\`',
    ].join('\n')).join('\n\n');
    const risk = estimateCompilePreflightRisk(buildCompilePromptSourceBundle(fences));
    expect(risk.generatedInventory.sidecarCount).toBeGreaterThanOrEqual(MAX_COMPILE_RISK_LIST_ITEMS);
    expect(risk.generatedInventory.pathReferences.length).toBeLessThanOrEqual(MAX_COMPILE_RISK_LIST_ITEMS);
  });

  it('counts all unique sidecar paths within one detected block', () => {
    const paths = Array.from({ length: MAX_COMPILE_RISK_LIST_ITEMS + 5 }, (_, i) => `sidecars/bulk-${i}.json`);
    const source = ['# PRD', '', '## Generated Sidecar Index', '', ...paths, '', 'Generated by eforge. Do not edit.', 'padding '.repeat(600)].join('\n');
    const risk = estimateCompilePreflightRisk(buildCompilePromptSourceBundle(source));
    expect(risk.generatedInventory.blockCount).toBe(1);
    expect(risk.generatedInventory.sidecarCount).toBe(paths.length);
    expect(risk.generatedInventory.pathReferences.length).toBe(MAX_COMPILE_RISK_LIST_ITEMS);
  });

  it('derives subsystem breadth and bounded evidence', () => {
    const source = 'Touch packages/engine, packages/client, packages/monitor, packages/console-ui, eforge-plugin, and packages/pi-eforge.';
    const risk = estimateCompilePreflightRisk(buildCompilePromptSourceBundle(source));
    expect(risk.subsystemBreadth.count).toBeGreaterThanOrEqual(4);
    expect(risk.subsystemBreadth.subsystems.length).toBeLessThanOrEqual(MAX_COMPILE_RISK_LIST_ITEMS);
    expect(risk.subsystemBreadth.evidence.length).toBeLessThanOrEqual(MAX_COMPILE_RISK_LIST_ITEMS);
  });

  it('records profile and scope signals', () => {
    const source = `${acPrd(40)}\n\npackages/engine packages/client packages/monitor packages/console-ui`;
    const bundle = buildCompilePromptSourceBundle(source);
    const errandRisk = estimateCompilePreflightRisk(bundle, { selectedProfile: 'errand' });
    expect(errandRisk.reasons).toContain('selected-profile:errand-scale-conflict');
    const expeditionRisk = estimateCompilePreflightRisk(bundle, { requestedPipelineScope: 'expedition' });
    expect(expeditionRisk.pipelineScope).toBe('expedition');
    expect(expeditionRisk.recommendation.action).not.toBe('retry-as-expedition');
  });

  it('honors explicit full-content allow-lists', () => {
    const byHeading = buildCompilePromptSourceBundle(generatedInventory(), { fullContentRequiredHeadings: ['generated inventory'] });
    const headingRisk = estimateCompilePreflightRisk(byHeading);
    expect(byHeading.promptSource).toContain(sentinel);
    expect(headingRisk.generatedInventory.detected).toBe(true);
    expect(headingRisk.generatedInventory.omittedBytes).toBe(0);

    const byPath = buildCompilePromptSourceBundle(generatedInventory('data/keep.json'), { fullContentRequiredPaths: ['data/keep.json'] });
    const pathRisk = estimateCompilePreflightRisk(byPath);
    expect(byPath.promptSource).toContain(sentinel);
    expect(pathRisk.generatedInventory.pathReferences).toContain('data/keep.json');
  });

  it('formats bounded appendix for overflow risk without raw omitted content', () => {
    const bundle = buildCompilePromptSourceBundle(generatedInventory());
    const risk = estimateCompilePreflightRisk(bundle, { requestedPipelineScope: 'excursion' });
    const appendix = formatCompilePreflightPromptAppend({ risk, bundle });
    expect(appendix).toContain('Compile Preflight Advisory');
    expect(appendix).toContain(`Source bytes: ${risk.sourceBytes}`);
    expect(appendix).toContain(`Prompt source bytes: ${risk.promptSourceBytes}`);
    expect(appendix).toContain(`Acceptance criteria count: ${risk.acceptanceCriteriaCount}`);
    expect(appendix).toContain(risk.recommendation.action);
    expect(appendix).not.toContain(sentinel);
    expect(Buffer.byteLength(appendix!, 'utf8')).toBeLessThan(4096);
  });
});
