import { describe, expect, it } from 'vitest';
import {
  buildCompilePromptSourceBundle,
  MODERATE_SOURCE_BYTES,
} from '@eforge-build/engine/compile-resilience/preflight';

const sentinel = 'RAW_GENERATED_SENTINEL_12345';

function smallPrd(): string {
  return ['# Small PRD', '', '## Acceptance Criteria', '', '- First criterion passes.', '- Second criterion passes.'].join('\n');
}

function generatedInventory(path = 'inventory/generated.json'): string {
  const rows = Array.from({ length: 220 }, (_, i) => `  { "path": "packages/engine/src/file-${i}.ts", "label": "${i === 177 ? sentinel : `item-${i}`}" }`).join(',\n');
  return ['# PRD', '', '## Generated Inventory', '', `\`\`\`json ${path}`, '[', rows, ']', '\`\`\`', '', '## Acceptance Criteria', '', '- The plan is generated.'].join('\n');
}

describe('compile prompt source bundle compaction', () => {
  it('leaves small PRDs unchanged', () => {
    const source = smallPrd();
    const bundle = buildCompilePromptSourceBundle(source);
    expect(bundle.promptSource).toBe(source);
    expect(bundle.compactions).toHaveLength(0);
    expect(bundle.analysis.acceptanceCriteriaCount).toBe(2);
  });

  it('passes oversized ordinary prose through without compaction', () => {
    const source = `# Large Ordinary\n\n${'Human-authored prose. '.repeat(Math.ceil(MODERATE_SOURCE_BYTES / 20) + 50)}`;
    const bundle = buildCompilePromptSourceBundle(source);
    expect(bundle.compactions).toHaveLength(0);
    expect(bundle.originalBytes).toBe(Buffer.byteLength(source, 'utf8'));
  });

  it('compacts embedded generated inventory and records bounded evidence', () => {
    const bundle = buildCompilePromptSourceBundle(generatedInventory());
    expect(bundle.compactions[0]).toMatchObject({ kind: 'generated-inventory' });
    expect(bundle.compactions[0].originalBytes).toBeGreaterThan(0);
    expect(bundle.compactions[0].contentHash).toMatch(/^[a-f0-9]{64}$/);
    expect(bundle.compactions[0].preservedSummary.length).toBeGreaterThan(0);
    expect(bundle.promptSource).toContain('eforge compile preflight compaction');
    expect(bundle.promptSource).not.toContain(sentinel);
    expect(bundle.analysis.detectedBlocks).toHaveLength(1);
    expect(bundle.analysis.detectedBlocks[0].omittedBytes).toBeGreaterThan(0);
  });

  it('derives acceptance criteria from full stripped source', () => {
    const source = [
      '# PRD',
      '',
      '## Acceptance Criteria',
      '',
      'Generated by eforge. Do not edit.',
      ...Array.from({ length: 71 }, (_, i) => `- Criterion ${i + 1} exits 0 for packages/engine packages/client packages/monitor packages/console-ui.`),
      sentinel,
    ].join('\n');
    const bundle = buildCompilePromptSourceBundle(source);
    expect(bundle.promptSource).not.toContain(sentinel);
    expect(bundle.analysis.acceptanceCriteriaCount).toBeGreaterThan(70);
  });

  it('honors explicit full-content allow-lists', () => {
    const byHeading = buildCompilePromptSourceBundle(generatedInventory(), { fullContentRequiredHeadings: ['generated inventory'] });
    expect(byHeading.promptSource).toContain(sentinel);
    expect(byHeading.analysis.detectedBlocks[0]?.omittedBytes).toBe(0);

    const byPath = buildCompilePromptSourceBundle(generatedInventory('data/keep.json'), { fullContentRequiredPaths: ['data/keep.json'] });
    expect(byPath.promptSource).toContain(sentinel);
    expect(byPath.analysis.detectedBlocks[0]?.pathReferences).toContain('data/keep.json');
  });
});
