import type { KanbanLane } from '../schema.js';
import { withProjectionStore } from './store.js';
import { listAllCompactEpicsFromStore, listAllCompactItemsFromStore } from './items.js';
import { getAssociatedPlanBuildLinksForItemsFromStore } from './links.js';
import { pageMetadata, paginateProjection } from './pagination.js';
import type { BoardActionInput, ListBoardCompactProjectionInput } from './types.js';

const LANE_TITLES: Record<KanbanLane, string> = { inbox: 'Inbox', ready: 'Planned', blocked: 'Blocked', 'in-progress': 'In Progress', done: 'Done', archive: 'Archive' };
const LANES: KanbanLane[] = ['inbox', 'ready', 'blocked', 'in-progress', 'done', 'archive'];
const PRIORITY: Record<string, number> = { critical: 0, high: 1, normal: 2, medium: 2, low: 3 };
function boardOrder(a: ReturnType<typeof listAllCompactItemsFromStore>[number], b: ReturnType<typeof listAllCompactItemsFromStore>[number]) { return LANES.indexOf(a.lane) - LANES.indexOf(b.lane) || Number(a.closed) - Number(b.closed) || (PRIORITY[a.priority] ?? 2) - (PRIORITY[b.priority] ?? 2) || (b.updatedAt ?? '').localeCompare(a.updatedAt ?? '') || a.id.localeCompare(b.id); }
function linksByItemId(links: ReturnType<typeof getAssociatedPlanBuildLinksForItemsFromStore>) { const byItem = new Map<string, typeof links>(); for (const link of links) for (const itemId of link.itemIds ?? []) byItem.set(itemId, [...(byItem.get(itemId) ?? []), link]); return byItem; }
export async function listBoardCompactProjection(cwd: string, input: ListBoardCompactProjectionInput): Promise<any> { return withProjectionStore<any>(cwd, (store) => { const scoped = listAllCompactItemsFromStore(store, { includeArchive: input.includeArchive === true, epic: input.epic, includeDependencies: input.includeDependencies !== false, includeLinks: false }); const filtered = scoped.filter((card) => (input.lane === undefined || card.lane === input.lane) && (input.includeClosed === true || !card.closed)).sort(boardOrder); const page = paginateProjection(filtered, input); const linksByItem = linksByItemId(getAssociatedPlanBuildLinksForItemsFromStore(store, page.entries.map((item) => item.id))); const pageEntries = page.entries.map((item) => ({ ...item, associatedLinks: (linksByItem.get(item.id) ?? []).slice(0, 20) })); const pageEpicIds = new Set(page.entries.map((item) => item.epic).filter((id): id is string => typeof id === 'string')); return { schemaVersion: 1 as const, items: pageEntries, total: filtered.length, limit: page.limit, offset: page.offset, ...(input.includeLaneCounts !== false ? { lanes: LANES.map((lane) => { const items = scoped.filter((i) => i.lane === lane); return { lane, title: LANE_TITLES[lane], count: items.length, openCount: items.filter((i) => !i.closed).length, closedCount: items.filter((i) => i.closed).length, ...(input.lane === lane ? { pagination: pageMetadata(page, filtered.length) } : {}) }; }), counts: { total: scoped.length, open: scoped.filter((i) => !i.closed).length, closed: scoped.filter((i) => i.closed).length } } : {}), ...(input.includeEpics === true ? { epics: listAllCompactEpicsFromStore(store).filter((e) => input.epic === undefined ? pageEpicIds.has(e.id) : e.id === input.epic) } : {}), pagination: pageMetadata(page, filtered.length) }; }, () => ({ schemaVersion: 1 as const, items: [], total: 0, limit: Math.min(Math.max(input.limit ?? 20, 1), 100), offset: Math.max(input.offset ?? 0, 0), lanes: [], ...(input.includeEpics === true ? { epics: [] } : {}), counts: { total: 0, open: 0, closed: 0 }, pagination: { limit: Math.min(Math.max(input.limit ?? 20, 1), 100), offset: Math.max(input.offset ?? 0, 0), returned: 0, hasMore: false } })); }
export async function buildBoardDebugProjection(cwd: string, input: BoardActionInput): Promise<any> { return withProjectionStore<any>(cwd, (store) => { const items = listAllCompactItemsFromStore(store, { includeArchive: input.includeArchive, epic: input.epic }); const epics = listAllCompactEpicsFromStore(store); const kanbanItems = items.map(({ updatedAt, ...item }) => ({ ...item, unresolvedDependsOn: item.unresolvedDependsOn ?? [], dependencies: [], dependents: [], notes: { claim: '', evidence: '', recheck: '', promotionPaths: '' }, recLanes: [], linkRows: [], failureEvidence: [] })); const lanes = LANES.map((lane) => ({ lane, title: LANE_TITLES[lane], items: kanbanItems.filter((i) => i.lane === lane) })); return { epics, items, lanes, blockedReasons: items.filter((i) => i.unresolvedDependsOn && i.unresolvedDependsOn.length > 0).map((i) => ({ itemId: i.id, reasons: i.reasons })), traceSummaries: [], lifecycleLinks: [], epicProgress: [], recommendationSummary: undefined, recommendationStatus: { state: 'missing', currentPath: '', statusPath: '', reasons: [], staleReasons: [] } }; }, () => ({ epics: [], items: [], lanes: LANES.map((lane) => ({ lane, title: LANE_TITLES[lane], items: [] })), blockedReasons: [], traceSummaries: [], lifecycleLinks: [], epicProgress: [], recommendationStatus: { state: 'missing', currentPath: '', statusPath: '', reasons: [], staleReasons: [] } })); }
export function renderBoardProjection(board: Awaited<ReturnType<typeof buildBoardDebugProjection>>): string { const lines = ['# eforge-plan board', '']; for (const lane of board.lanes as Array<{ title: string; items: Array<{ id: string; status: string; title: string; reasons: string[] }> }>) { lines.push(`## ${lane.title}`, ''); if (lane.items.length === 0) lines.push('_No items._', ''); for (const item of lane.items) lines.push(`- **${item.id}** (${item.status}) ${item.title}${item.reasons.length ? ` — ${item.reasons.join('; ')}` : ''}`); lines.push(''); } return lines.join('\n'); }
