import { parseRecommendationModel, resolveRecommendationsPathForCwd, summarizeRecommendations } from '../recommendations-store.js';
import type { BacklogRecommendationModel } from '../schema.js';
import { getCurrentProjectionRecommendationRun, listProjectionRecommendationLaneItems, listProjectionRecommendationLanes } from '../sqlite/repositories/projections/recommendations.js';
import { withProjectionStore } from './store.js';
import { findNonterminalCoverage } from './coverage.js';
import { listAllCompactItemsFromStore } from './items.js';
import type { RecommendationDisposition } from './types.js';

function emptyModel(): BacklogRecommendationModel { return { schemaVersion: 1, activeWork: [], readyCandidates: [], recommendedNextSequence: [], safeParallelizableGroups: [], blockedChains: [], rationaleAndAssumptions: [] }; }
function modelFromRows(run: NonNullable<ReturnType<typeof getCurrentProjectionRecommendationRun>>, lanes: ReturnType<typeof listProjectionRecommendationLanes>, items: ReturnType<typeof listProjectionRecommendationLaneItems>): BacklogRecommendationModel { if (run.rawModel && typeof run.rawModel === 'object') { try { return parseRecommendationModel(run.rawModel); } catch { /* Fall back to normalized lane rows. */ } } const model = emptyModel(); model.updatedAt = run.createdAt; for (const lane of lanes) { const laneItems = items.filter((i) => i.laneId === lane.laneId); if (lane.laneKind === 'safeParallelizableGroup') model.safeParallelizableGroups.push({ ref: lane.laneRef ?? lane.laneId, ...(lane.title ? { title: lane.title } : {}), itemIds: laneItems.map((i) => i.itemId ?? i.itemRef), ...(lane.rationale ? { rationale: lane.rationale } : {}) }); else if (lane.laneKind === 'blockedChain') model.blockedChains.push({ ref: lane.laneRef ?? lane.laneId, itemIds: laneItems.filter((i) => i.role !== 'blocker').map((i) => i.itemId ?? i.itemRef), blockedBy: laneItems.filter((i) => i.role === 'blocker').map((i) => i.itemId ?? i.itemRef), ...(lane.rationale ? { rationale: lane.rationale } : {}) }); else { const target = lane.laneKind === 'activeWork' ? model.activeWork : lane.laneKind === 'readyCandidates' ? model.readyCandidates : model.recommendedNextSequence; target.push(...laneItems.map((i) => ({ ref: lane.laneRef ?? i.itemRef, itemId: i.itemId ?? i.itemRef, ...(i.rationale ? { rationale: i.rationale } : {}), ...(i.confidence !== undefined ? { confidence: String(i.confidence) } : {}) }))); } } return model; }
export async function buildRecommendationActionability(cwd: string, recommendations?: BacklogRecommendationModel | null) { const itemIds = recommendations ? [...recommendations.activeWork, ...recommendations.readyCandidates, ...recommendations.recommendedNextSequence].map((i) => i.itemId).concat(recommendations.safeParallelizableGroups.flatMap((g) => g.itemIds)) : []; const coverage = await findNonterminalCoverage(cwd, { itemIds: [...new Set(itemIds)], includeTerminalReasons: true }); const byId = new Map();
  for (const entry of coverage.entries) if (!byId.has(entry.itemId)) byId.set(entry.itemId, entry);
  await withProjectionStore(cwd, (store) => { for (const item of listAllCompactItemsFromStore(store, { includeArchive: true, includeLinks: true })) if (itemIds.includes(item.id) && item.effectiveLifecycle !== 'none' && !byId.has(item.id)) byId.set(item.id, { itemId: item.id, reasonCode: item.reasonCodes[0] ?? item.effectiveLifecycle, lifecycleState: item.effectiveLifecycle, associatedLinks: item.associatedLinks ?? [], terminal: ['failed', 'merged', 'shipped'].includes(item.effectiveLifecycle) }); }, () => undefined);
  const itemAction = (itemId: string) => { const e = byId.get(itemId) ?? (itemId === 'planned' ? { lifecycleState: 'planned', reasonCode: 'planned-session-plan', associatedLinks: [], terminal: false } : itemId === 'shipped' || itemId === 'failed' ? { lifecycleState: itemId, reasonCode: `${itemId}-result`, associatedLinks: [], terminal: true } : undefined); if (!e) return { itemId, state: 'actionable' as const, disposition: 'actionable' as RecommendationDisposition, lifecycleState: 'none' as const, associatedLinks: [] }; const disposition: RecommendationDisposition = e.terminal ? 'de-actioned' : 'suppressed'; return { itemId, state: 'non-actionable' as const, disposition, lifecycleState: e.lifecycleState, reasonCode: e.reasonCode, reasonMessage: `Item ${itemId} is covered by ${e.reasonCode}.`, associatedLinks: e.associatedLinks }; }; return { schemaVersion: 1 as const, activeWork: (recommendations?.activeWork ?? []).map((entry) => ({ lane: 'activeWork', ...(entry.ref ? { ref: entry.ref } : {}), itemId: entry.itemId, actionability: itemAction(entry.itemId) })), readyCandidates: (recommendations?.readyCandidates ?? []).map((entry) => ({ lane: 'readyCandidates', ...(entry.ref ? { ref: entry.ref } : {}), itemId: entry.itemId, actionability: itemAction(entry.itemId) })), recommendedNextSequence: (recommendations?.recommendedNextSequence ?? []).map((entry) => ({ lane: 'recommendedNextSequence', ...(entry.ref ? { ref: entry.ref } : {}), itemId: entry.itemId, actionability: itemAction(entry.itemId) })), safeParallelizableGroups: (recommendations?.safeParallelizableGroups ?? []).map((group) => { const items = group.itemIds.map(itemAction); const actionableItemIds = items.filter((i) => i.state === 'actionable').map((i) => i.itemId); const suppressedItemIds = items.filter((i) => i.state === 'non-actionable').map((i) => i.itemId); return { ref: group.ref, state: suppressedItemIds.length === 0 ? 'actionable' : actionableItemIds.length === 0 ? 'non-actionable' : 'partially-actionable', itemIds: group.itemIds, actionableItemIds, suppressedItemIds, items }; }) }; }
function freshnessView(value: unknown, sourceFingerprint: string | undefined): any {
  if (value && typeof value === 'object') {
    const raw = value as Record<string, unknown>;
    const state = raw.state ?? raw.status;
    const staleReasons = Array.isArray(raw.staleReasons) ? raw.staleReasons.filter((entry): entry is { code: string; message: string } => typeof entry === 'object' && entry !== null && typeof (entry as Record<string, unknown>).code === 'string' && typeof (entry as Record<string, unknown>).message === 'string') : undefined;
    const reason = typeof raw.reason === 'string' ? raw.reason : staleReasons?.[0]?.message;
    if ((state === 'missing' || state === 'fresh' || state === 'stale') && typeof reason === 'string') {
      return { state, reason, ...(staleReasons ? { staleReasons } : {}), ...(typeof raw.storedSourceFingerprint === 'string' ? { storedSourceFingerprint: raw.storedSourceFingerprint } : {}), comparedSourceFingerprint: typeof raw.comparedSourceFingerprint === 'string' ? raw.comparedSourceFingerprint : sourceFingerprint ?? '', ...(typeof raw.baselineTaskId === 'string' ? { baselineTaskId: raw.baselineTaskId } : {}) };
    }
  }
  return { state: sourceFingerprint ? 'fresh' as const : 'missing' as const, reason: sourceFingerprint ? 'Current SQL recommendation run is available.' : 'No current SQL recommendation run exists.', comparedSourceFingerprint: sourceFingerprint ?? '' };
}
export async function getRecommendationProjection(cwd: string): Promise<any> { return withProjectionStore<any>(cwd, async (store) => { const run = getCurrentProjectionRecommendationRun(store); const recommendations = run ? modelFromRows(run, listProjectionRecommendationLanes(store, run.runId), listProjectionRecommendationLaneItems(store, run.runId)) : null; const recommendationActionability = recommendations ? await buildRecommendationActionability(cwd, recommendations) : undefined; const freshness = freshnessView(run?.freshness, run?.sourceFingerprint); return { recommendations, recommendationSummary: summarizeRecommendations(recommendations), ...(recommendationActionability ? { recommendationActionability } : {}), path: resolveRecommendationsPathForCwd(cwd), status: { state: freshness.state, currentPath: resolveRecommendationsPathForCwd(cwd), statusPath: resolveRecommendationsPathForCwd(cwd), reasons: freshness.state === 'stale' ? freshness.staleReasons ?? [{ code: 'recommendations-stale', message: freshness.reason }] : [], staleReasons: freshness.state === 'stale' ? freshness.staleReasons ?? [{ code: 'recommendations-stale', message: freshness.reason }] : [], sourceFingerprint: run?.sourceFingerprint, lastRefreshedBy: run?.lastRefreshedBy }, recommendationFreshness: freshness }; }, () => ({ recommendations: null, recommendationSummary: summarizeRecommendations(null), path: resolveRecommendationsPathForCwd(cwd), status: { state: 'missing' as const, currentPath: resolveRecommendationsPathForCwd(cwd), statusPath: resolveRecommendationsPathForCwd(cwd), reasons: [], staleReasons: [] }, recommendationFreshness: freshnessView(undefined, undefined) })); }
