import type { EforgePlanStore, EpicRow, EpicUpsert, SectionUpsert, UserStatus } from '../types.js';
import { USER_STATUSES } from '../types.js';
import { validateDomain } from '../validation.js';
import { all, cleanUndefined, jsonText, one, optionalString, parseJsonColumn, run } from './sql.js';
interface EpicDbRow { id: string; title: string; body: string; user_status: string; priority: string | null; source: string | null; created_at: string | null; updated_at: string | null; last_checked_at: string | null; stale_after: string | null; frontmatter_json: string; body_sha256: string | null; record_sha256: string | null; import_origin: string | null; import_path: string | null }
export function rowToEpic(row: EpicDbRow): EpicRow { return cleanUndefined({ id: row.id, title: row.title, body: row.body, userStatus: row.user_status as UserStatus, priority: optionalString(row.priority), source: optionalString(row.source), createdAt: optionalString(row.created_at), updatedAt: optionalString(row.updated_at), lastCheckedAt: optionalString(row.last_checked_at), staleAfter: optionalString(row.stale_after), frontmatter: parseJsonColumn('epics','frontmatter_json', row.frontmatter_json, {}), bodySha256: optionalString(row.body_sha256), recordSha256: optionalString(row.record_sha256), importOrigin: optionalString(row.import_origin), importPath: optionalString(row.import_path) }); }
export function upsertEpic(store: EforgePlanStore, input: EpicUpsert): EpicRow {
  validateDomain('userStatus', input.userStatus, USER_STATUSES);
  run(store, `INSERT INTO epics (id,title,body,user_status,priority,source,created_at,updated_at,last_checked_at,stale_after,frontmatter_json,body_sha256,record_sha256,import_origin,import_path) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title, body=excluded.body, user_status=excluded.user_status, priority=excluded.priority, source=excluded.source, created_at=excluded.created_at, updated_at=excluded.updated_at, last_checked_at=excluded.last_checked_at, stale_after=excluded.stale_after, frontmatter_json=excluded.frontmatter_json, body_sha256=excluded.body_sha256, record_sha256=excluded.record_sha256, import_origin=excluded.import_origin, import_path=excluded.import_path`, input.id, input.title, input.body ?? '', input.userStatus, input.priority ?? null, input.source ?? null, input.createdAt ?? null, input.updatedAt ?? null, input.lastCheckedAt ?? null, input.staleAfter ?? null, jsonText(input.frontmatter, {}), input.bodySha256 ?? null, input.recordSha256 ?? null, input.importOrigin ?? null, input.importPath ?? null);
  return getEpic(store, input.id)!;
}
export function getEpic(store: EforgePlanStore, id: string): EpicRow | undefined { const row = one<EpicDbRow>(store, 'SELECT * FROM epics WHERE id = ?', id); return row ? rowToEpic(row) : undefined; }
export function listEpics(store: EforgePlanStore): EpicRow[] { return all<EpicDbRow>(store, 'SELECT * FROM epics ORDER BY id').map(rowToEpic); }
export function replaceEpicTags(store: EforgePlanStore, epicId: string, tags: string[]): void { store.transaction(() => { run(store, 'DELETE FROM epic_tags WHERE epic_id = ?', epicId); for (const tag of tags) run(store, 'INSERT OR IGNORE INTO epic_tags (epic_id, tag) VALUES (?, ?)', epicId, tag); }); }
export function replaceEpicSections(store: EforgePlanStore, epicId: string, sections: SectionUpsert[]): void { store.transaction(() => { run(store, 'DELETE FROM epic_sections WHERE epic_id = ?', epicId); for (const s of sections) run(store, 'INSERT INTO epic_sections (epic_id, section_name, content, content_sha256) VALUES (?, ?, ?, ?)', epicId, s.sectionName, s.content ?? '', s.contentSha256 ?? null); }); }
