import type { BacklogItemRow, BacklogItemUpsert, DependencyStatus, EforgePlanStore, ItemDependencyRow, ItemDependencyUpsert, SectionUpsert, UserStatus } from '../types.js';
import { DEPENDENCY_STATUSES, USER_STATUSES } from '../types.js';
import { validateDomain } from '../validation.js';
import { all, cleanUndefined, jsonText, one, optionalString, parseJsonColumn, run } from './sql.js';

interface ItemDbRow { id: string; title: string; body: string; user_status: string; priority: string | null; source: string | null; created_at: string | null; updated_at: string | null; last_checked_at: string | null; stale_after: string | null; epic_ref: string | null; epic_id: string | null; frontmatter_json: string; body_sha256: string | null; record_sha256: string | null; import_origin: string | null; import_path: string | null }
export function rowToBacklogItem(row: ItemDbRow): BacklogItemRow {
  return cleanUndefined({ id: row.id, title: row.title, body: row.body, userStatus: row.user_status as UserStatus, priority: optionalString(row.priority), source: optionalString(row.source), createdAt: optionalString(row.created_at), updatedAt: optionalString(row.updated_at), lastCheckedAt: optionalString(row.last_checked_at), staleAfter: optionalString(row.stale_after), epicRef: optionalString(row.epic_ref), epicId: optionalString(row.epic_id), frontmatter: parseJsonColumn('backlog_items', 'frontmatter_json', row.frontmatter_json, {}), bodySha256: optionalString(row.body_sha256), recordSha256: optionalString(row.record_sha256), importOrigin: optionalString(row.import_origin), importPath: optionalString(row.import_path) });
}
export function upsertBacklogItem(store: EforgePlanStore, input: BacklogItemUpsert): BacklogItemRow {
  validateDomain('userStatus', input.userStatus, USER_STATUSES);
  run(store, `INSERT INTO backlog_items (id,title,body,user_status,priority,source,created_at,updated_at,last_checked_at,stale_after,epic_ref,epic_id,frontmatter_json,body_sha256,record_sha256,import_origin,import_path)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET title=excluded.title, body=excluded.body, user_status=excluded.user_status, priority=excluded.priority, source=excluded.source, created_at=excluded.created_at, updated_at=excluded.updated_at, last_checked_at=excluded.last_checked_at, stale_after=excluded.stale_after, epic_ref=excluded.epic_ref, epic_id=excluded.epic_id, frontmatter_json=excluded.frontmatter_json, body_sha256=excluded.body_sha256, record_sha256=excluded.record_sha256, import_origin=excluded.import_origin, import_path=excluded.import_path`,
    input.id, input.title, input.body ?? '', input.userStatus, input.priority ?? null, input.source ?? null, input.createdAt ?? null, input.updatedAt ?? null, input.lastCheckedAt ?? null, input.staleAfter ?? null, input.epicRef ?? null, input.epicId ?? null, jsonText(input.frontmatter, {}), input.bodySha256 ?? null, input.recordSha256 ?? null, input.importOrigin ?? null, input.importPath ?? null);
  return getBacklogItem(store, input.id)!;
}
export function getBacklogItem(store: EforgePlanStore, id: string): BacklogItemRow | undefined { const row = one<ItemDbRow>(store, 'SELECT * FROM backlog_items WHERE id = ?', id); return row ? rowToBacklogItem(row) : undefined; }
export function listBacklogItems(store: EforgePlanStore): BacklogItemRow[] { return all<ItemDbRow>(store, 'SELECT * FROM backlog_items ORDER BY id').map(rowToBacklogItem); }
export function replaceBacklogItemTags(store: EforgePlanStore, itemId: string, tags: string[]): void { store.transaction(() => { run(store, 'DELETE FROM backlog_item_tags WHERE item_id = ?', itemId); for (const tag of tags) run(store, 'INSERT OR IGNORE INTO backlog_item_tags (item_id, tag) VALUES (?, ?)', itemId, tag); }); }
export function replaceBacklogItemSections(store: EforgePlanStore, itemId: string, sections: SectionUpsert[]): void { store.transaction(() => { run(store, 'DELETE FROM backlog_item_sections WHERE item_id = ?', itemId); for (const s of sections) run(store, 'INSERT INTO backlog_item_sections (item_id, section_name, content, content_sha256) VALUES (?, ?, ?, ?)', itemId, s.sectionName, s.content ?? '', s.contentSha256 ?? null); }); }
export function replaceItemDependencies(store: EforgePlanStore, itemId: string, dependencies: ItemDependencyUpsert[]): void { store.transaction(() => { run(store, 'DELETE FROM item_dependencies WHERE item_id = ?', itemId); for (const d of dependencies) { const dependencyStatus = d.dependencyStatus ?? 'unknown'; validateDomain('dependencyStatus', dependencyStatus, DEPENDENCY_STATUSES); run(store, 'INSERT INTO item_dependencies (item_id, dependency_ref, dependency_kind, dependency_status, resolved_dependency_item_id, source_path, diagnostic_json) VALUES (?, ?, ?, ?, ?, ?, ?)', itemId, d.dependencyRef, d.dependencyKind ?? 'depends-on', dependencyStatus, d.resolvedDependencyItemId ?? null, d.sourcePath ?? null, jsonText(d.diagnostic)); } }); }
export function listItemDependencies(store: EforgePlanStore, itemId: string): ItemDependencyRow[] { return all<Record<string, unknown>>(store, 'SELECT * FROM item_dependencies WHERE item_id = ? ORDER BY dependency_ref', itemId).map((row) => cleanUndefined({ itemId: row.item_id as string, dependencyRef: row.dependency_ref as string, dependencyKind: row.dependency_kind as string, dependencyStatus: row.dependency_status as DependencyStatus, resolvedDependencyItemId: optionalString(row.resolved_dependency_item_id), sourcePath: optionalString(row.source_path), diagnostic: parseJsonColumn('item_dependencies','diagnostic_json', row.diagnostic_json) })); }
