import type { EforgePlanStore, LaneKind, RecommendationItemRole, RecommendationLaneItemUpsert, RecommendationLaneRow, RecommendationLaneUpsert, RecommendationRunRow, RecommendationRunUpsert } from '../types.js';
import { LANE_KINDS, RECOMMENDATION_ITEM_ROLES } from '../types.js';
import { validateDomain } from '../validation.js';
import { boolToInt, cleanUndefined, intToBool, jsonText, one, optionalString, parseJsonColumn, run } from './sql.js';
export function rowToRecommendationRun(row: Record<string, unknown>): RecommendationRunRow { return cleanUndefined({ runId: row.run_id as string, sourceFingerprint: optionalString(row.source_fingerprint), createdAt: optionalString(row.created_at), appliedAt: optionalString(row.applied_at), lastRefreshedBy: optionalString(row.last_refreshed_by), isCurrent: intToBool(row.is_current), rawModel: parseJsonColumn('recommendation_runs','raw_model_json', row.raw_model_json), summary: parseJsonColumn('recommendation_runs','summary_json', row.summary_json), freshness: parseJsonColumn('recommendation_runs','freshness_json', row.freshness_json), importOrigin: optionalString(row.import_origin), importPath: optionalString(row.import_path) }); }
export function upsertRecommendationRun(store: EforgePlanStore, input: RecommendationRunUpsert): RecommendationRunRow { run(store, `INSERT INTO recommendation_runs (run_id,source_fingerprint,created_at,applied_at,last_refreshed_by,is_current,raw_model_json,summary_json,freshness_json,import_origin,import_path) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET source_fingerprint=excluded.source_fingerprint, created_at=excluded.created_at, applied_at=excluded.applied_at, last_refreshed_by=excluded.last_refreshed_by, is_current=excluded.is_current, raw_model_json=excluded.raw_model_json, summary_json=excluded.summary_json, freshness_json=excluded.freshness_json, import_origin=excluded.import_origin, import_path=excluded.import_path`, input.runId, input.sourceFingerprint ?? null, input.createdAt ?? null, input.appliedAt ?? null, input.lastRefreshedBy ?? null, boolToInt(input.isCurrent, false), jsonText(input.rawModel), jsonText(input.summary), jsonText(input.freshness), input.importOrigin ?? null, input.importPath ?? null); return rowToRecommendationRun(one(store, 'SELECT * FROM recommendation_runs WHERE run_id = ?', input.runId)!); }
export function rowToRecommendationLane(row: Record<string, unknown>): RecommendationLaneRow { return cleanUndefined({ laneId: row.lane_id as string, runId: row.run_id as string, laneKind: row.lane_kind as LaneKind, laneRef: row.lane_ref === '' ? undefined : optionalString(row.lane_ref), title: optionalString(row.title), sequence: row.sequence as number, profile: optionalString(row.profile), rationale: optionalString(row.rationale) }); }
export function upsertRecommendationLane(store: EforgePlanStore, input: RecommendationLaneUpsert): RecommendationLaneRow { validateDomain('laneKind', input.laneKind, LANE_KINDS); run(store, `INSERT INTO recommendation_lanes (lane_id,run_id,lane_kind,lane_ref,title,sequence,profile,rationale) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(lane_id) DO UPDATE SET run_id=excluded.run_id, lane_kind=excluded.lane_kind, lane_ref=excluded.lane_ref, title=excluded.title, sequence=excluded.sequence, profile=excluded.profile, rationale=excluded.rationale`, input.laneId, input.runId, input.laneKind, input.laneRef ?? '', input.title ?? null, input.sequence ?? 0, input.profile ?? null, input.rationale ?? null); return rowToRecommendationLane(one(store, 'SELECT * FROM recommendation_lanes WHERE lane_id = ?', input.laneId)!); }
export function replaceRecommendationLaneItems(store: EforgePlanStore, laneId: string, items: RecommendationLaneItemUpsert[]): void { store.transaction(() => { run(store, 'DELETE FROM recommendation_lane_items WHERE lane_id = ?', laneId); for (const item of items) { validateDomain('role', item.role, RECOMMENDATION_ITEM_ROLES); run(store, 'INSERT INTO recommendation_lane_items (lane_id,item_ref,item_id,role,sequence,rationale,confidence) VALUES (?,?,?,?,?,?,?)', laneId, item.itemRef, item.itemId ?? null, item.role, item.sequence ?? null, item.rationale ?? null, item.confidence ?? null); } }); }
