import type { EforgePlanStore, SearchDocumentRow, SearchDocumentType, SearchDocumentUpsert, SearchIndexDirtyInput, SearchIndexStateRow } from '../types.js';
import { SEARCH_DOCUMENT_TYPES } from '../types.js';
import { validateDomain } from '../validation.js';
import { boolToInt, cleanUndefined, intToBool, nowIso, one, optionalString, run } from './sql.js';
export function rowToSearchDocument(row: Record<string, unknown>): SearchDocumentRow { return cleanUndefined({ documentType: row.document_type as SearchDocumentType, documentId: row.document_id as string, title: optionalString(row.title), tagsText: optionalString(row.tags_text), summaryText: optionalString(row.summary_text), bodyText: optionalString(row.body_text), itemIdsText: optionalString(row.item_ids_text), epicIdsText: optionalString(row.epic_ids_text), recommendationRefsText: optionalString(row.recommendation_refs_text), sourceSha256: optionalString(row.source_sha256), updatedAt: optionalString(row.updated_at), dirty: intToBool(row.dirty) }); }
export function replaceSearchDocument(store: EforgePlanStore, input: SearchDocumentUpsert): SearchDocumentRow { validateDomain('documentType', input.documentType, SEARCH_DOCUMENT_TYPES); store.transaction(() => { run(store, `INSERT INTO search_documents (document_type,document_id,title,tags_text,summary_text,body_text,item_ids_text,epic_ids_text,recommendation_refs_text,source_sha256,updated_at,dirty) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(document_type,document_id) DO UPDATE SET title=excluded.title, tags_text=excluded.tags_text, summary_text=excluded.summary_text, body_text=excluded.body_text, item_ids_text=excluded.item_ids_text, epic_ids_text=excluded.epic_ids_text, recommendation_refs_text=excluded.recommendation_refs_text, source_sha256=excluded.source_sha256, updated_at=excluded.updated_at, dirty=excluded.dirty`, input.documentType, input.documentId, input.title ?? null, input.tagsText ?? null, input.summaryText ?? null, input.bodyText ?? null, input.itemIdsText ?? null, input.epicIdsText ?? null, input.recommendationRefsText ?? null, input.sourceSha256 ?? null, input.updatedAt ?? null, boolToInt(input.dirty, false)); run(store, 'DELETE FROM search_documents_fts WHERE document_type = ? AND document_id = ?', input.documentType, input.documentId); run(store, 'INSERT INTO search_documents_fts (document_type,document_id,title,tags_text,summary_text,body_text,item_ids_text,epic_ids_text,recommendation_refs_text) VALUES (?,?,?,?,?,?,?,?,?)', input.documentType, input.documentId, input.title ?? '', input.tagsText ?? '', input.summaryText ?? '', input.bodyText ?? '', input.itemIdsText ?? '', input.epicIdsText ?? '', input.recommendationRefsText ?? ''); }); return rowToSearchDocument(one(store, 'SELECT * FROM search_documents WHERE document_type = ? AND document_id = ?', input.documentType, input.documentId)!); }
export function markSearchIndexDirty(store: EforgePlanStore, input: SearchIndexDirtyInput): void { markSearchIndexDirtyBatch(store, [input]); }
export function markSearchIndexDirtyBatch(store: EforgePlanStore, inputs: readonly SearchIndexDirtyInput[]): void { store.transaction(() => { for (const input of inputs) { validateDomain('documentType', input.documentType, SEARCH_DOCUMENT_TYPES); const markedAt = input.markedAt ?? nowIso(); run(store, `INSERT INTO search_index_dirty_records (document_type,document_id,reason,marked_at) VALUES (?,?,?,?) ON CONFLICT(document_type,document_id) DO UPDATE SET reason=excluded.reason, marked_at=excluded.marked_at`, input.documentType, input.documentId, input.reason ?? null, markedAt); run(store, 'UPDATE search_documents SET dirty = 1 WHERE document_type = ? AND document_id = ?', input.documentType, input.documentId); run(store, 'UPDATE search_index_state SET dirty = 1, dirty_since = COALESCE(dirty_since, ?), dirty_reason = ? WHERE id = 1', markedAt, input.reason ?? null); } }); }
export function clearSearchIndexDirty(store: EforgePlanStore, input: { rebuiltAt?: string } = {}): void { store.transaction(() => { run(store, 'DELETE FROM search_index_dirty_records'); run(store, 'UPDATE search_documents SET dirty = 0'); run(store, 'UPDATE search_index_state SET dirty = 0, dirty_since = NULL, dirty_reason = NULL, last_rebuilt_at = ? WHERE id = 1', input.rebuiltAt ?? nowIso()); }); }
export function getSearchIndexState(store: EforgePlanStore): SearchIndexStateRow { const row = one<Record<string, unknown>>(store, 'SELECT * FROM search_index_state WHERE id = 1')!; return cleanUndefined({ id: 1 as const, dirty: intToBool(row.dirty), dirtySince: optionalString(row.dirty_since), dirtyReason: optionalString(row.dirty_reason), lastRebuiltAt: optionalString(row.last_rebuilt_at) }); }
