import type { EforgePlanStore, SessionPlanEpicLinkInput, SessionPlanItemLinkInput, SessionPlanRow, SessionPlanUpsert } from '../types.js';
import { all, cleanUndefined, jsonText, one, optionalString, parseJsonColumn, run } from './sql.js';
export function rowToSessionPlan(row: Record<string, unknown>): SessionPlanRow { return cleanUndefined({ session: row.session as string, path: optionalString(row.path), topic: optionalString(row.topic), status: optionalString(row.status), planningType: optionalString(row.planning_type), planningDepth: optionalString(row.planning_depth), profile: optionalString(row.profile), agentProfile: optionalString(row.agent_profile), eforgeSessionId: optionalString(row.eforge_session_id), submittedAt: optionalString(row.submitted_at), createdAt: optionalString(row.created_at), updatedAt: optionalString(row.updated_at), summaryText: optionalString(row.summary_text), artifactBodyHash: optionalString(row.artifact_body_hash), frontmatter: parseJsonColumn('session_plans','frontmatter_json', row.frontmatter_json, {}), readinessSummary: parseJsonColumn('session_plans','readiness_summary_json', row.readiness_summary_json), importOrigin: optionalString(row.import_origin), importPath: optionalString(row.import_path) }); }
export function upsertSessionPlan(store: EforgePlanStore, input: SessionPlanUpsert): SessionPlanRow { run(store, `INSERT INTO session_plans (session,path,topic,status,planning_type,planning_depth,profile,agent_profile,eforge_session_id,submitted_at,created_at,updated_at,summary_text,artifact_body_hash,frontmatter_json,readiness_summary_json,import_origin,import_path) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(session) DO UPDATE SET path=excluded.path, topic=excluded.topic, status=excluded.status, planning_type=excluded.planning_type, planning_depth=excluded.planning_depth, profile=excluded.profile, agent_profile=excluded.agent_profile, eforge_session_id=excluded.eforge_session_id, submitted_at=excluded.submitted_at, created_at=excluded.created_at, updated_at=excluded.updated_at, summary_text=excluded.summary_text, artifact_body_hash=excluded.artifact_body_hash, frontmatter_json=excluded.frontmatter_json, readiness_summary_json=excluded.readiness_summary_json, import_origin=excluded.import_origin, import_path=excluded.import_path`, input.session, input.path ?? null, input.topic ?? null, input.status ?? null, input.planningType ?? null, input.planningDepth ?? null, input.profile ?? null, input.agentProfile ?? null, input.eforgeSessionId ?? null, input.submittedAt ?? null, input.createdAt ?? null, input.updatedAt ?? null, input.summaryText ?? null, input.artifactBodyHash ?? null, jsonText(input.frontmatter, {}), jsonText(input.readinessSummary), input.importOrigin ?? null, input.importPath ?? null); return rowToSessionPlan(one(store, 'SELECT * FROM session_plans WHERE session = ?', input.session)!); }
export function getSessionPlan(store: EforgePlanStore, session: string): SessionPlanRow | undefined { const row = one<Record<string, unknown>>(store, 'SELECT * FROM session_plans WHERE session = ?', session); return row ? rowToSessionPlan(row) : undefined; }
export function listSessionPlans(store: EforgePlanStore): SessionPlanRow[] { return all<Record<string, unknown>>(store, 'SELECT * FROM session_plans ORDER BY updated_at DESC, session').map(rowToSessionPlan); }
export function replaceAllSessionPlanItems(store: EforgePlanStore, input: SessionPlanItemLinkInput): void { store.transaction(() => { run(store, 'DELETE FROM session_plan_items WHERE session = ?', input.session); linkSessionPlanItems(store, input); }); }
export function replaceAllSessionPlanEpics(store: EforgePlanStore, input: SessionPlanEpicLinkInput): void { store.transaction(() => { run(store, 'DELETE FROM session_plan_epics WHERE session = ?', input.session); linkSessionPlanEpics(store, input); }); }
export function linkSessionPlanItems(store: EforgePlanStore, input: SessionPlanItemLinkInput): void { store.transaction(() => { for (const item of input.items) run(store, `INSERT INTO session_plan_items (session,item_ref,item_id,role,provenance,source_task_id,source_recommendation_ref,promoted_at,sequence) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(session,item_ref,role,provenance) DO UPDATE SET item_id=excluded.item_id, source_task_id=excluded.source_task_id, source_recommendation_ref=excluded.source_recommendation_ref, promoted_at=excluded.promoted_at, sequence=excluded.sequence`, input.session, item.itemRef, item.itemId ?? null, item.role, item.provenance, item.sourceTaskId ?? null, item.sourceRecommendationRef ?? null, item.promotedAt ?? null, item.sequence ?? null); }); }
export function linkSessionPlanEpics(store: EforgePlanStore, input: SessionPlanEpicLinkInput): void { store.transaction(() => { for (const epic of input.epics) run(store, `INSERT INTO session_plan_epics (session,epic_ref,epic_id,role,provenance,source_task_id,source_recommendation_ref,promoted_at,sequence) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(session,epic_ref,role,provenance) DO UPDATE SET epic_id=excluded.epic_id, source_task_id=excluded.source_task_id, source_recommendation_ref=excluded.source_recommendation_ref, promoted_at=excluded.promoted_at, sequence=excluded.sequence`, input.session, epic.epicRef, epic.epicId ?? null, epic.role, epic.provenance, epic.sourceTaskId ?? null, epic.sourceRecommendationRef ?? null, epic.promotedAt ?? null, epic.sequence ?? null); }); }
