/**
 * Browser-safe entrypoint for @eforge-build/client.
 *
 * Exports everything from the main index that is safe to use in a browser
 * context. Specifically excludes:
 *   - lockfile.ts  (uses node:fs)
 *   - daemon-client.ts  (uses node:child_process, node:fs)
 *   - profile-utils.ts  (uses node:fs via daemon-client)
 *
 * session-stream.ts is safe: it branches on `typeof EventSource !== 'undefined'`
 * at runtime, using fetch in browser contexts. The `node:http` import in
 * session-stream.ts is only exercised on the Node path.
 */

export {
  API_ROUTES,
  buildPath,
  RECOVERY_SIDECAR_COMPILE_SCOPE_CONTEXT_ACTIONS,
  RECOVERY_SIDECAR_COMPILE_SCOPE_CONTEXT_REASON_MAX_BYTES,
  RecoverySidecarContinueRepairOptionSchema,
  RecoverySidecarCompileScopeContextActionSchema,
  RecoverySidecarCompileScopeContextOptionSchema,
  RecoverySidecarRecoveryOptionSchema,
} from './routes.js';
export {
  EXTENSION_AGENT_TASK_ACTIVITY_LOG_MAX_ENTRIES,
  EXTENSION_AGENT_TASK_ACTIVITY_MESSAGE_MAX_LENGTH,
} from './extension-agent-tasks/constants.js';
export { isTransientTransportError } from './transient-transport.js';
export * from './efficiency-metrics.js';
export type {
  ApiRoute,
  EnqueueRequest,
  AutoBuildSetRequest,
  StopDaemonRequest,
  VersionResponse,
  RecoverRequest,
  RecoverResponse,
  ReadSidecarRequest,
  RecoverySidecarContinueRepairEligibilitySource,
  RecoverySidecarContinueRepairEligibility,
  RecoverySidecarSchemaVersion,
  RecoverySidecarContinueRepairOption,
  RecoverySidecarCompileScopeContextAction,
  RecoverySidecarCompileScopeContextOption,
  RecoverySidecarRecoveryOption,
  RecoveryVerdictSidecar,
  RecoveryAppliedMetadata,
  ReadSidecarResponse,
  ApplyRecoveryRequest,
  ApplyRecoveryResponse,
  AcceptSuccessReasonCategory,
  AcceptSuccessLandingAction,
  AcceptSuccessPreviewRequest,
  AcceptSuccessCleanupEffect,
  AcceptSuccessAuditFields,
  AcceptSuccessDependentCandidate,
  AcceptSuccessCleanupResult,
  AcceptSuccessLandingResult,
  AcceptSuccessDependentResult,
  AcceptSuccessAppliedSummary,
  AcceptSuccessPreviewResponse,
  AcceptSuccessRequest,
  AcceptSuccessResponse,
  QueueControlStatus,
  QueuePriorityRequest,
  QueuePriorityResponse,
  QueueRemoveResponse,
  QueueDependencyOverrideRequest,
  QueueDependencyOverrideResponse,
  RecoveryGuidancePrepareRequest,
  RecoveryGuidancePatchStatus,
  RecoveryGuidancePatchedPlan,
  RecoveryGuidancePrepareResponse,
  FailedEnqueuesResponse,
  FailedEnqueueReenqueueRequest,
  FailedEnqueueReenqueueResponse,
  FailedEnqueueDismissRequest,
  FailedEnqueueDismissResponse,
  SchedulerPauseResponse,
  SchedulerResumeResponse,
  QueueHoldRequest,
  QueueHoldResponse,
  QueueUnholdRequest,
  QueueUnholdResponse,
  QueueControlLocation,
  QueueCascadeOperation,
  QueueCascadeApplyResultStatus,
  QueueCascadeStrategy,
  QueueCascadeEffect,
  QueueCascadeRunningOwnership,
  QueueCascadeAffectedItem,
  QueueCascadeExpectedAffected,
  QueueCascadePreviewRequest,
  QueueCascadePreviewResponse,
  QueueCascadeApplyRequest,
  QueueCascadeApplyItemResult,
  QueueCascadeApplyResponse,
  ContinueRepairRequest,
  ContinueRepairResponse,
  ContinueRepairEligibilityRequest,
  ContinueRepairEligibilityResponse,
  ContinueRepairArtifactAvailability,
  SessionPlanStatusWire,
  PlanningTypeWire,
  PlanningDepthWire,
  SkippedDimensionWire,
  SessionPlanListEntryWire,
  SessionPlanDataWire,
  SessionPlanListResponse,
  SessionPlanShowResponse,
  SessionPlanCreateRequest,
  SessionPlanCreateResponse,
  SessionPlanSetSectionRequest,
  SessionPlanSetSectionResponse,
  SessionPlanSkipDimensionRequest,
  SessionPlanSkipDimensionResponse,
  SessionPlanSetStatusRequest,
  SessionPlanSetStatusResponse,
  SessionPlanSelectDimensionsRequest,
  SessionPlanSelectDimensionsResponse,
  SessionPlanReadinessResponse,
  SessionPlanMigrateLegacyRequest,
  SessionPlanMigrateLegacyResponse,
  SessionPlanListRequest,
  StackLayersResponse,
  StackSyncRequest,
  StackSyncResponse,
  StackSyncOutcomeWire,
  StackSyncActiveBuildSkipWire,
  StackSyncProviderCommandWire,
  StackSyncStatusWire,
  StackSyncStatusResponse,
  ExtensionAgentTaskActivityEntry,
  ExtensionAgentTaskCancelRequest,
  ExtensionAgentTaskCancelResponse,
  ExtensionAgentTaskGetRequest,
  ExtensionAgentTaskGetResponse,
  ExtensionAgentTaskBacklogCurationItemProgress,
  ExtensionAgentTaskBacklogCurationProgress,
  ExtensionAgentTaskKind,
  ExtensionAgentTaskRecord,
  ExtensionAgentTaskSanitizedMetadata,
  ExtensionAgentTaskStartRequest,
  ExtensionAgentTaskStartResponse,
  ExtensionAgentTaskStatus,
  EforgePlanPlanningDraftInput,
  EforgePlanPlanningDraftResult,
} from './routes.js';

export type {
  QueueRecoveryStrategy,
  QueueRecoveryStrategyWire,
  QueueRecoveryLocation,
  QueueRecoveryNodeRole,
  QueueRecoveryNode,
  QueueRecoveryEdge,
  QueueRecoveryOperationKind,
  QueueRecoveryMovePrdOperation,
  QueueRecoveryRemoveRecoverySidecarsOperation,
  QueueRecoveryOperation,
  QueueRecoveryOperationStatus,
  QueueRecoveryOperationResult,
  QueueRecoveryNotice,
  QueueRecoveryDependencyStatus,
  QueueRecoveryDependencyClassification,
  QueueRecoveryDispatchPreflightItem,
  QueueRecoveryDispatchPreflightSummary,
  QueueRecoveryRemoveDependsOnRepairAction,
  QueueRecoverySetStackParentRepairAction,
  QueueRecoveryRepairAction,
  QueueRecoveryFrontmatterMetadataSummary,
  QueueRecoveryRepairResult,
  QueueRecoveryAnalyzeRequest,
  QueueRecoveryAnalyzeResponse,
  QueueRecoveryApplyRequest,
  QueueRecoveryApplyResponse,
} from './queue-recovery.js';
export {
  QUEUE_RECOVERY_STRATEGY_RETRY_AND_REACTIVATE,
  isQueueRecoveryStrategy,
} from './queue-recovery.js';
export {
  fetchQueueRecoveryAnalysis,
  applyQueueRecovery,
} from './browser-queue-recovery.js';
export {
  updateQueuePriority,
  removeQueueItem,
  overrideQueueDependency,
  holdQueueItem,
  unholdQueueItem,
  previewQueueCascade,
  applyQueueCascade,
} from './browser-queue-control.js';
export { fetchFailedEnqueues, reenqueueFailedEnqueue, dismissFailedEnqueue } from './browser-failed-enqueue.js';
export { pauseScheduler, resumeScheduler } from './browser-scheduler.js';

export {
  fetchRecoverySidecar,
  triggerRecoveryAnalysis,
  applySidecarRecovery,
  startContinueRepair,
  fetchContinueRepairEligibility,
  fetchAcceptSuccessPreview,
  acceptRecoverySuccess,
  prepareRecoveryGuidance,
} from './browser-recovery.js';

export { ACCEPT_SUCCESS_REASON_CATEGORIES } from './routes.js';

export {
  fetchExtensionContributionManifest,
  invokeExtensionAction,
} from './browser-extension-contributions.js';
export {
  formatExtensionContributionOutput,
  formatExtensionContributionOutputText,
  formatExtensionContributionDetail,
  formatExtensionContributionDetailText,
  formatExtensionContributionFailedInvocationEnvelope,
  formatExtensionContributionFailedInvocationEnvelopeText,
  formatExtensionContributionList,
  formatExtensionContributionListText,
} from './extension-contribution-output-formatting.js';
export type {
  ExtensionContributionFormattedOutputKind,
  FormatExtensionContributionOutputOptions,
  FormattedExtensionContributionOutput,
  FormatExtensionContributionHostTextOptions,
} from './extension-contribution-output-formatting.js';
export type {
  ExtensionHostContributionDetailOptions,
  ExtensionHostContributionDetailResponse,
  ExtensionHostContributionEntry,
  ExtensionHostContributionFailedInvocationEnvelope,
  ExtensionHostContributionInputSummary,
  ExtensionHostContributionKind,
  ExtensionHostContributionListResponse,
  ExtensionHostContributionProjection,
  ExtensionHostContributionProjectionOptions,
} from './api/extension-contribution-dispatch.js';
// --- eforge:region extension-agent-task-contracts ---
export * from './extension-agent-tasks.js';
export {
  cancelExtensionAgentTask,
  getExtensionAgentTask,
  startExtensionAgentTask,
} from './browser-extension-agent-tasks.js';
// --- eforge:endregion extension-agent-task-contracts ---
export {
  readWorkstationBridgeContext,
  navigateWorkstation,
  onWorkstationRoute,
} from './browser-workstation-routing.js';
export type { WorkstationBridgeContext } from './browser-workstation-routing.js';
export {
  EXTENSION_CONTRIBUTION_MANIFEST_SCHEMA_VERSION,
  CONSOLE_WORKSTATION_BROWSER_SDK_VERSION,
  CONSOLE_WORKSTATION_BUNDLE_ASSET_ID_PATTERN,
  CONSOLE_WORKSTATION_BUNDLE_ASSET_URL_PATTERN,
  CONSOLE_WORKSTATION_BUNDLE_SHA256_PATTERN,
  CONSOLE_WORKSTATION_FRAME_URL_PATTERN,
  ExtensionActionBindingManifestSchema,
  ExtensionActionInvokeErrorCodeSchema,
  ExtensionActionInvokeFailureResponseSchema,
  ExtensionActionInvokeRequestSchema,
  ExtensionActionInvokeResponseSchema,
  ExtensionActionInvokeSuccessResponseSchema,
  ExtensionActionValidationErrorSchema,
  ExtensionActionManifestEntrySchema,
  ExtensionActionOutputProfileSchema,
  ExtensionAvailabilityDiagnosticSchema,
  ExtensionCapabilityRequirementSchema,
  ExtensionContributionAvailabilitySchema,
  ExtensionContributionRequirementsSchema,
  ExtensionDependencyRequirementSchema,
  ExtensionActionRequestedByHostSchema,
  ExtensionActionRequestedBySchema,
  ExtensionActionSideEffectSchema,
  ExtensionContributionDiagnosticSchema,
  ExtensionContributionManifestResponseSchema,
  ExtensionDeepLinkManifestEntrySchema,
  ExtensionJsonObjectSchema,
  ExtensionJsonValueSchema,
  ConsoleContributionBlockSchema,
  ConsoleContributionManifestEntrySchema,
  ConsoleContributionRendererIdSchema,
  ConsoleWorkstationFrameBundleAssetRefSchema,
  ConsoleWorkstationFrameBundleManifestSchema,
  ConsoleWorkstationSubviewManifestEntrySchema,
  ConsoleWorkstationSrcDocManifestEntrySchema,
  ConsoleWorkstationFrameBundleManifestEntrySchema,
  ConsoleWorkstationManifestEntrySchema,
  IntegrationCommandManifestEntrySchema,
  parseExtensionActionInvokeRequest,
  parseExtensionActionInvokeResponse,
  parseExtensionContributionManifest,
  safeParseExtensionActionInvokeRequest,
  safeParseExtensionActionInvokeResponse,
  safeParseExtensionContributionManifest,
} from './extension-contributions.js';
export type {
  ConsoleContributionBlock,
  ConsoleContributionManifestEntry,
  ConsoleContributionRendererId,
  ConsoleWorkstationFrameBundleAssetRef,
  ConsoleWorkstationFrameBundleManifest,
  ConsoleWorkstationSubviewManifestEntry,
  ConsoleWorkstationSrcDocManifestEntry,
  ConsoleWorkstationFrameBundleManifestEntry,
  ConsoleWorkstationManifestEntry,
  ExtensionActionBindingManifest,
  ExtensionAvailabilityDiagnostic,
  ExtensionCapabilityRequirement,
  ExtensionContributionAvailability,
  ExtensionContributionRequirements,
  ExtensionDependencyRequirement,
  ExtensionActionInvokeErrorCode,
  ExtensionActionInvokeFailureResponse,
  ExtensionActionInvokeRequest,
  ExtensionActionInvokeResponse,
  ExtensionActionInvokeSuccessResponse,
  ExtensionActionValidationError,
  ExtensionActionManifestEntry,
  ExtensionActionOutputProfile,
  ExtensionActionRequestedBy,
  ExtensionActionRequestedByHost,
  ExtensionActionSideEffect,
  ExtensionContributionDiagnostic,
  ExtensionContributionManifestResponse,
  ExtensionDeepLinkManifestEntry,
  ExtensionJsonObject,
  ExtensionJsonValue,
  IntegrationCommandManifestEntry,
} from './extension-contributions.js';

export type {
  SessionPlanSetStatusWire,
  SessionPlanSetStrategyWire,
  SessionPlanSetChildKindWire,
  SessionPlanSetDiagnosticCodeWire,
  SessionPlanSetExternalRefWire,
  SessionPlanSetDiagnosticWire,
  SessionPlanSetChildValidationSummaryWire,
  SessionPlanSetChildSummaryWire,
  SessionPlanSetAnchorSummaryWire,
  SessionPlanSetSummaryWire,
  SessionPlanSetValidationResultWire,
  SessionPlanSetListEntryWire,
  SessionPlanSetListRequest,
  SessionPlanSetListResponse,
  SessionPlanSetShowRequest,
  SessionPlanSetShowResponse,
  SessionPlanSetValidateRequest,
  SessionPlanSetValidateResponse,
} from './session-plan-set.js';

export type * from './types.js';

export {
  parseSseChunk,
  subscribeWithSnapshot,
} from './session-stream.js';
export type {
  SessionSummary,
  SubscribeOptions,
  DaemonStreamEvent,
  ParsedSseBlock,
  DaemonStreamSnapshot,
  SessionStreamSnapshot,
  SubscribeWithSnapshotFrame,
} from './session-stream.js';

export { aggregateSessionSummary } from './aggregate-session-summary.js';
export { classifyRunStatus, isFailedRunStatus } from './run-status.js';
export type { RunStatusClass } from './run-status.js';

export {
  eventRegistry,
  DAEMON_EVENT_TYPES,
  getEventSummary,
  isPersistedDaemonEventType,
} from './event-registry.js';
export type {
  EventMeta,
  EventScope,
  ProjectableState,
} from './event-registry.js';

// Only the numeric constant is browser-safe; verifyApiVersion and
// clearApiVersionCache depend on Node-only lockfile/fs modules and are
// available on the main (Node) entrypoint only.
export { DAEMON_API_VERSION } from './api-version-const.js';

export type {
  EforgeEvent,
  AgentRole,
  AgentResultData,
  EforgeResult,
  ClarificationQuestion,
  ReviewFixIssueReference,
  ReviewFixIssueStatus,
  ReviewIssue,
  ReviewIssueId,
  ValidationRepairClass,
  PlanFile,
  OrchestrationConfig,
  PlanState,
  EforgeState,
  PrdValidationGap,
  AcceptanceCriterionVerdict,
  AcceptanceCriteriaConflict,
  TestIssue,
  BuildFailureSummary,
  LandedCommit,
  PlanSummaryEntry,
  FailingPlanEntry,
  ReconciliationReport,
  EforgeStatus,
  QueueEvent,
  QueueDispatchFailureStage,
  StalenessVerdict,
  RecoveryVerdict,
  ReviewPerspective,
  // --- eforge:region build-completion-recovery ---
  EvaluationIssueOutcome,
  // --- eforge:endregion build-completion-recovery ---
  ReviewPerspectiveKey,
  AgentTerminalSubtype,
  ShardScope,
  PipelineComposition,
  BuildDecision,
  PlanningDecision,
  PlanningDecisionEvent,
  StackProvider,
  StackProviderOperationKind,
  StackProviderConflictKind,
  LandingPublicationAction,
  StackLayerStatus,
  StackArtifactRef,
  StackLayerWire,
  TerminalFailureScope,
  TerminalFailureEnvelope,
  BuildResumeArtifactSource,
  BuildResumeArtifactPlan,
  BuildResumeArtifactsEvent,
  BoundedDiagnosticOptions,
  BoundedValidationDiagnostic,
  CompileArtifactSummary,
  CompileContextGuardDiagnostics,
  CompileContextGuardLimits,
  CompileContextGuardMetadataSource,
  CompileRecoveryAction,
  CompileScopeContextFailure,
  CompileScopeContextFailureEvent,
  PlannerContextObservation,
  PlannerInspectionBudgetDiagnostics,
  PlannerInspectionIdentifiers,
  PlannerInspectionOmittedCounts,
  PlannerInspectionSourceBuildContext,
  PlannerInspectionSummary,
  PlannerInspectionSummaryEvent,
  PlanningMapReduceAtom,
  PlanningMapReduceAtomEdge,
  PlanningMapReduceAtomReason,
  PlanningMapReduceAtomStatus,
  PlanningMapReduceEventType,
  PlanningMapReduceReduceNode,
  PlanningMapReduceReduceStatus,
} from './events.js';


export { SEVERITY_ORDER, isAlwaysYieldedAgentEvent, REVIEW_PERSPECTIVES, EvaluationIssueOutcomeSchema, PlanningDecisionSchema,
  AcceptanceCriterionVerdictSchema, AcceptanceCriteriaConflictSchema,
  FailedEnqueueInfoSchema, QueueItemCapabilitySchema, QueueItemCapabilitiesSchema, QueueItemHoldSchema,
  ReviewFixIssueReferenceSchema, ReviewFixIssueStatusSchema, ReviewIssueIdSchema,
  ReviewPerspectiveKeySchema,
  isBuiltInReviewPerspective,
  StackProviderSchema, StackProviderOperationKindSchema, StackProviderConflictKindSchema, LandingPublicationActionSchema, StackLayerStatusSchema, StackArtifactRefSchema, StackLayerWireSchema,
  TerminalFailureScopeSchema, TerminalFailureEnvelopeSchema,
  BuildResumeArtifactSourceSchema, BuildResumeArtifactPlanSchema, BuildResumeArtifactsEventSchema,
  BoundedDiagnosticOptionsSchema, BoundedValidationDiagnosticSchema, CompileArtifactSummarySchema,
  CompileContextGuardDiagnosticsSchema, CompileContextGuardLimitsSchema, CompileContextGuardMetadataSourceSchema,
  CompileRecoveryActionSchema,
  CompileScopeContextFailureKindSchema, CompileScopeContextFailureSchema, CompileScopeContextSourceSchema,
  PlannerContextObservationSchema, PlannerInspectionBudgetDiagnosticsSchema, PlannerInspectionIdentifiersSchema,
  PlannerInspectionOmittedCountsSchema, PlannerInspectionSourceBuildContextSchema, PlannerInspectionSummarySchema, PlannerInspectionSourceContextTextSchema,
  PlannerInspectionSummaryTextSchema, MAX_PLANNER_INSPECTION_CAVEATS, MAX_PLANNER_INSPECTION_IMPLEMENTATION_AREAS,
  MAX_PLANNER_INSPECTION_IMPORTANT_FINDINGS, MAX_PLANNER_INSPECTION_OBSERVED_FACTS, MAX_PLANNER_INSPECTION_RELEVANT_FILES,
  MAX_PLANNER_INSPECTION_SOURCE_CONTEXT_LENGTH, MAX_PLANNER_INSPECTION_UNRESOLVED_QUESTIONS,
  MAX_COMPILE_RISK_LIST_ITEMS,
  MAX_COMPILE_SCOPE_CONTEXT_EXPLANATION_LENGTH, MAX_VALIDATION_DIAGNOSTIC_EXCERPT_LENGTH, MAX_VALIDATION_DIAGNOSTIC_MESSAGE_LENGTH,
} from './events.js';

export {
  DecompositionFailureEvidenceSchema,
  PlanningCoverageSummarySchema,
  PlanningCriterionCoverageSchema,
  PlanningDecompositionLimitsSchema,
  PlanningDecompositionUnitStatusSchema,
  PlanningDecompositionUnitSummarySchema,
  PlanningObservedBudgetPressureSchema,
  PlanningScheduleBlockedPairSchema,
  PlanningScheduleDecisionSchema,
  PlanningScheduleWaitingReasonSchema,
  PlanningSourceSliceSummarySchema,
  PlanningSplitAttemptEvidenceSchema,
  PlanningUnitBudgetSchema,
  PlanningUnitBudgetEntrySchema,
  PlanningUnitConstraintSchema,
  PlanningUnresolvedCriterionSchema,
  capPlanningDecompositionString,
  projectPlanningCoverageSummaryForWire,
  projectPlanningDecompositionUnitSummaryForWire,
  PLANNING_DECOMPOSITION_EVENT_TYPES,
  PLANNING_DECOMPOSITION_MAX_BLOCKED_PAIRS,
  PLANNING_DECOMPOSITION_MAX_COVERAGE_OMISSIONS,
  PLANNING_DECOMPOSITION_MAX_CRITERIA,
  PLANNING_DECOMPOSITION_MAX_DEPENDENCIES,
  PLANNING_DECOMPOSITION_MAX_LIST_ITEMS,
  PLANNING_DECOMPOSITION_MAX_SOURCE_SLICES,
  PLANNING_DECOMPOSITION_MAX_SPLIT_ATTEMPTS,
  PLANNING_DECOMPOSITION_MAX_STRING_LENGTH,
  PLANNING_DECOMPOSITION_MAX_UNITS,
  PLANNING_DECOMPOSITION_MAX_UNRESOLVED_CRITERIA,
} from './events/shared/planning-decomposition.js';
export type {
  DecompositionFailureEvidence,
  PlanningCoverageSummary,
  PlanningCriterionCoverage,
  PlanningDecompositionEventType,
  PlanningDecompositionLimits,
  PlanningDecompositionUnitStatus,
  PlanningDecompositionUnitSummary,
  PlanningObservedBudgetPressure,
  PlanningScheduleBlockedPair,
  PlanningScheduleDecision,
  PlanningScheduleWaitingReason,
  PlanningSourceSliceSummary,
  PlanningSplitAttemptEvidence,
  PlanningUnitBudget,
  PlanningUnitBudgetEntry,
  PlanningUnitConstraint,
  PlanningUnresolvedCriterion,
} from './events/shared/planning-decomposition.js';

export type {
  PlanningDecompositionStartEvent,
  PlanningDecompositionUnitQueuedEvent,
  PlanningDecompositionUnitRunningEvent,
  PlanningDecompositionUnitProgressEvent,
  PlanningDecompositionUnitCompletedEvent,
  PlanningDecompositionUnitSkippedEvent,
  PlanningDecompositionUnitFailedEvent,
  PlanningDecompositionScheduleEvent,
  PlanningDecompositionBudgetEvent,
  PlanningDecompositionCompactHandoffEvent,
  PlanningDecompositionSynthesisCompleteEvent,
} from './events.js';
