/**
 * Wire event types and schemas for the eforge daemon SSE stream.
 *
 * Types are derived from TypeBox schemas exposed by `events.schemas.ts` (a
 * compatibility facade over `events/` implementation modules) and re-exported
 * here so engine and docs-generator code can import event and snapshot schemas
 * from './events.js' or the public `@eforge-build/client/events` subpath.
 *
 * The engine re-exports these types from `@eforge-build/client` so callers
 * that already depend on the client do not need to add the engine as a
 * dependency.
 */

export type {
  TerminalFailureScope,
  TerminalFailureEnvelope,
  EforgeEvent,
  DaemonRunUpsertEvent,
  AgentRole,
  AgentResultData,
  EforgeResult,
  ClarificationQuestion,
  ReviewFixIssueReference,
  ReviewFixIssueStatus,
  ReviewIssue,
  ReviewIssueId,
  ValidationRepairClass,
  PlanFile,
  OrchestrationConfig,
  PlanState,
  EforgeState,
  PrdValidationGap,
  AcceptanceCriterionVerdict,
  AcceptanceCriteriaConflict,
  TestIssue,
  BuildFailureSummary,
  LandedCommit,
  PlanSummaryEntry,
  FailingPlanEntry,
  ReconciliationReport,
  EforgeStatus,
  QueueEvent,
  QueueDispatchFailureStage,
  StalenessVerdict,
  RecoveryVerdict,
  ReviewPerspective,
  // --- eforge:region build-completion-recovery ---
  EvaluationIssueOutcome,
  // --- eforge:endregion build-completion-recovery ---
  ReviewPerspectiveKey,
  AgentTerminalSubtype,
  ShardScope,
  PipelineComposition,
  BuildDecision,
  PlanningDecision,
  PlanningDecisionEvent,
  AutoBuildDesired,
  AutoBuildRuntimeMode,
  AutoBuildSchedulerState,
  AutoBuildTransitionDetail,
  StackProvider,
  StackProviderOperationKind,
  StackProviderConflictKind,
  LandingPublicationAction,
  StackLayerStatus,
  StackArtifactRef,
  StackLayerWire,
  BaseSyncEvent,
  BuildResumeStartEvent,
  BuildResumeStateEvent,
  BuildResumeIneligibleEvent,
  BuildResumeArtifactSource,
  BuildResumeArtifactPlan,
  BuildResumeArtifactsEvent,
  BuildResumeCompleteEvent,
  BoundedDiagnosticOptions,
  BoundedValidationDiagnostic,
  CompileArtifactSummary,
  CompileContextGuardDiagnostics,
  CompileContextGuardLimits,
  CompileContextGuardMetadataSource,
  CompileRecoveryAction,
  CompileScopeContextFailure,
  CompileScopeContextFailureEvent,
  PlannerContextObservation,
  PlannerInspectionBudgetDiagnostics,
  PlannerInspectionIdentifiers,
  PlannerInspectionOmittedCounts,
  PlannerInspectionSourceBuildContext,
  PlannerInspectionSummary,
  PlannerInspectionSummaryEvent,
  PlanningDecompositionStartEvent,
  PlanningDecompositionUnitQueuedEvent,
  PlanningDecompositionUnitRunningEvent,
  PlanningDecompositionUnitProgressEvent,
  PlanningDecompositionUnitCompletedEvent,
  PlanningDecompositionUnitSkippedEvent,
  PlanningDecompositionUnitFailedEvent,
  PlanningDecompositionScheduleEvent,
  PlanningDecompositionBudgetEvent,
  PlanningDecompositionCompactHandoffEvent,
  PlanningDecompositionSynthesisCompleteEvent,
} from './events.schemas.js';

export {
  SEVERITY_ORDER,
  isAlwaysYieldedAgentEvent,
  REVIEW_PERSPECTIVES,
  // --- eforge:region build-completion-recovery ---
  EvaluationIssueOutcomeSchema,
  // --- eforge:endregion build-completion-recovery ---
  AgentTerminalSubtypeSchema,
  BuildDecisionSchema,
  PlanningDecisionSchema,
  AcceptanceCriterionVerdictSchema,
  AcceptanceCriteriaConflictSchema,
  safeParseEforgeEvent,
  parseEforgeEvent,
  safeParseDaemonStreamSnapshot,
  safeParseSessionStreamSnapshot,
  ReviewFixIssueReferenceSchema,
  ReviewFixIssueStatusSchema,
  ReviewIssueIdSchema,
  ReviewPerspectiveKeySchema,
  isBuiltInReviewPerspective,
  StackProviderSchema,
  StackProviderOperationKindSchema,
  StackProviderConflictKindSchema,
  FailedEnqueueInfoSchema,
  QueueItemCapabilitiesSchema,
  QueueItemCapabilitySchema,
  QueueItemHoldSchema,
  LandingPublicationActionSchema,
  StackLayerStatusSchema,
  StackArtifactRefSchema,
  StackLayerWireSchema,
  TerminalFailureScopeSchema,
  TerminalFailureEnvelopeSchema,
  BuildResumeArtifactSourceSchema,
  BuildResumeArtifactPlanSchema,
  BuildResumeArtifactsEventSchema,
  QueueDispatchFailureStageSchema,
  BoundedDiagnosticOptionsSchema,
  BoundedValidationDiagnosticSchema,
  CompileArtifactSummarySchema,
  CompileContextGuardDiagnosticsSchema,
  CompileContextGuardLimitsSchema,
  CompileContextGuardMetadataSourceSchema,
  CompileRecoveryActionSchema,
  CompileScopeContextFailureKindSchema,
  CompileScopeContextFailureSchema,
  CompileScopeContextSourceSchema,
  PlannerContextObservationSchema,
  PlannerInspectionBudgetDiagnosticsSchema,
  PlannerInspectionIdentifiersSchema,
  PlannerInspectionOmittedCountsSchema,
  PlannerInspectionSourceBuildContextSchema,
  PlannerInspectionSummarySchema,
  PlannerInspectionSourceContextTextSchema,
  PlannerInspectionSummaryTextSchema,
  MAX_PLANNER_INSPECTION_CAVEATS,
  MAX_PLANNER_INSPECTION_IMPLEMENTATION_AREAS,
  MAX_PLANNER_INSPECTION_IMPORTANT_FINDINGS,
  MAX_PLANNER_INSPECTION_OBSERVED_FACTS,
  MAX_PLANNER_INSPECTION_RELEVANT_FILES,
  MAX_PLANNER_INSPECTION_SOURCE_CONTEXT_LENGTH,
  MAX_PLANNER_INSPECTION_UNRESOLVED_QUESTIONS,
  MAX_COMPILE_RISK_LIST_ITEMS,
  MAX_COMPILE_SCOPE_CONTEXT_EXPLANATION_LENGTH,
  MAX_VALIDATION_DIAGNOSTIC_EXCERPT_LENGTH,
  MAX_VALIDATION_DIAGNOSTIC_MESSAGE_LENGTH,
  RECOVERY_AUTO_RESUME_MAX_ATTEMPTS,
} from './events.schemas.js';

export { DaemonStreamSnapshotSchema, EforgeEventSchema } from './events.schemas.js';

export {
  DecompositionFailureEvidenceSchema,
  PlanningCoverageSummarySchema,
  PlanningCriterionCoverageSchema,
  PlanningDecompositionLimitsSchema,
  PlanningDecompositionUnitStatusSchema,
  PlanningDecompositionUnitSummarySchema,
  PlanningObservedBudgetPressureSchema,
  PlanningScheduleBlockedPairSchema,
  PlanningScheduleDecisionSchema,
  PlanningScheduleWaitingReasonSchema,
  PlanningSourceSliceSummarySchema,
  PlanningSplitAttemptEvidenceSchema,
  PlanningUnitBudgetSchema,
  PlanningUnitBudgetEntrySchema,
  PlanningUnitConstraintSchema,
  PlanningUnresolvedCriterionSchema,
  capPlanningDecompositionString,
  projectPlanningCoverageSummaryForWire,
  projectPlanningDecompositionUnitSummaryForWire,
  PLANNING_DECOMPOSITION_EVENT_TYPES,
  PLANNING_DECOMPOSITION_MAX_BLOCKED_PAIRS,
  PLANNING_DECOMPOSITION_MAX_COVERAGE_OMISSIONS,
  PLANNING_DECOMPOSITION_MAX_CRITERIA,
  PLANNING_DECOMPOSITION_MAX_DEPENDENCIES,
  PLANNING_DECOMPOSITION_MAX_LIST_ITEMS,
  PLANNING_DECOMPOSITION_MAX_SOURCE_SLICES,
  PLANNING_DECOMPOSITION_MAX_SPLIT_ATTEMPTS,
  PLANNING_DECOMPOSITION_MAX_STRING_LENGTH,
  PLANNING_DECOMPOSITION_MAX_UNITS,
  PLANNING_DECOMPOSITION_MAX_UNRESOLVED_CRITERIA,
} from './events/shared/planning-decomposition.js';
export type {
  DecompositionFailureEvidence,
  PlanningCoverageSummary,
  PlanningCriterionCoverage,
  PlanningDecompositionEventType,
  PlanningDecompositionLimits,
  PlanningDecompositionUnitStatus,
  PlanningDecompositionUnitSummary,
  PlanningObservedBudgetPressure,
  PlanningScheduleBlockedPair,
  PlanningScheduleDecision,
  PlanningScheduleWaitingReason,
  PlanningSourceSliceSummary,
  PlanningSplitAttemptEvidence,
  PlanningUnitBudget,
  PlanningUnitBudgetEntry,
  PlanningUnitConstraint,
  PlanningUnresolvedCriterion,
} from './events/shared/planning-decomposition.js';
export {
  PlanningMapReduceAtomSchema,
  PlanningMapReduceAtomEdgeSchema,
  PlanningMapReduceAtomReasonSchema,
  PlanningMapReduceAtomStatusSchema,
  PlanningMapReduceReduceNodeSchema,
  PlanningMapReduceReduceStatusSchema,
  PLANNING_MAP_REDUCE_EVENT_TYPES,
  PLANNING_MAP_REDUCE_MAX_ATOMS,
  PLANNING_MAP_REDUCE_MAX_EDGES,
  PLANNING_MAP_REDUCE_MAX_IDS,
  PLANNING_MAP_REDUCE_MAX_NODES,
  PLANNING_MAP_REDUCE_MAX_STRING_LENGTH,
} from './events/variants/planning-map-reduce.js';
export type {
  PlanningMapReduceAtom,
  PlanningMapReduceAtomEdge,
  PlanningMapReduceAtomReason,
  PlanningMapReduceAtomStatus,
  PlanningMapReduceEventType,
  PlanningMapReduceReduceNode,
  PlanningMapReduceReduceStatus,
} from './events/variants/planning-map-reduce.js';
