/**
 * Compatibility facade for eforge daemon SSE event schemas.
 *
 * The wire protocol is implemented in focused modules under
 * `packages/client/src/events/`. `EforgeEvent` remains derived from
 * `EforgeEventSchema` via `Static<typeof EforgeEventSchema>`, and public
 * consumers continue to import through @eforge-build/client barrels.
 */

export { REVIEW_PERSPECTIVES } from './events/constants.js';
export {
  BoundedDiagnosticOptionsSchema,
  BoundedValidationDiagnosticSchema,
  CompileArtifactSummarySchema,
  CompileContextGuardDiagnosticsSchema,
  CompileContextGuardLimitsSchema,
  CompileContextGuardMetadataSourceSchema,
  CompileRecoveryActionSchema,
  CompileScopeContextFailureKindSchema,
  CompileScopeContextFailureSchema,
  CompileScopeContextSourceSchema,
  PlannerContextObservationSchema,
  PlannerInspectionBudgetDiagnosticsSchema,
  PlannerInspectionIdentifiersSchema,
  PlannerInspectionOmittedCountsSchema,
  PlannerInspectionSourceBuildContextSchema,
  PlannerInspectionSummarySchema,
  PlannerInspectionSourceContextTextSchema,
  PlannerInspectionSummaryTextSchema,
  MAX_PLANNER_INSPECTION_CAVEATS,
  MAX_PLANNER_INSPECTION_IMPLEMENTATION_AREAS,
  MAX_PLANNER_INSPECTION_IMPORTANT_FINDINGS,
  MAX_PLANNER_INSPECTION_OBSERVED_FACTS,
  MAX_PLANNER_INSPECTION_RELEVANT_FILES,
  MAX_PLANNER_INSPECTION_SOURCE_CONTEXT_LENGTH,
  MAX_PLANNER_INSPECTION_UNRESOLVED_QUESTIONS,
  MAX_COMPILE_RISK_LIST_ITEMS,
  MAX_COMPILE_SCOPE_CONTEXT_EXPLANATION_LENGTH,
  MAX_VALIDATION_DIAGNOSTIC_EXCERPT_LENGTH,
  MAX_VALIDATION_DIAGNOSTIC_MESSAGE_LENGTH,
} from './events/shared/compile-resilience.js';
export {
  AcceptanceCriteriaConflictSchema,
  AcceptanceCriterionVerdictSchema,
  AgentTerminalSubtypeSchema,
  BuildResumeArtifactPlanSchema,
  BuildResumeArtifactSourceSchema,
  BuildResumeArtifactsEventSchema,
  EvaluationIssueOutcomeSchema,
  FailedEnqueueInfoSchema,
  QueueItemCapabilitiesSchema,
  QueueItemCapabilitySchema,
  QueueItemHoldSchema,
  LandingActionSchema,
  LandingPublicationActionSchema,
  ReviewFixIssueReferenceSchema,
  ReviewFixIssueStatusSchema,
  ReviewIssueIdSchema,
  ReviewPerspectiveKeySchema,
  StackArtifactRefSchema,
  StackLandingStatusSchema,
  StackLayerLandingWireSchema,
  StackLayerStatusSchema,
  StackLayerWireSchema,
  StackProviderConflictKindSchema,
  StackProviderOperationKindSchema,
  StackProviderSchema,
  TerminalFailureEnvelopeSchema,
  TerminalFailureScopeSchema,
} from './events/shared/schemas.js';
export { BuildDecisionSchema, PlanningDecisionEventSchema, PlanningDecisionSchema } from './events/decisions.js';
export { QueueDispatchFailureStageSchema } from './events/queue-events.js';
export { RuntimeChoiceSourceSchema, RuntimeChoiceFallbackReasonSchema } from './events/shared/agent-fields.js';

export {
  DecompositionFailureEvidenceSchema,
  PlanningCoverageSummarySchema,
  PlanningCriterionCoverageSchema,
  PlanningDecompositionLimitsSchema,
  PlanningDecompositionUnitStatusSchema,
  PlanningDecompositionUnitSummarySchema,
  PlanningObservedBudgetPressureSchema,
  PlanningScheduleBlockedPairSchema,
  PlanningScheduleDecisionSchema,
  PlanningScheduleWaitingReasonSchema,
  PlanningSourceSliceSummarySchema,
  PlanningSplitAttemptEvidenceSchema,
  PlanningUnitBudgetSchema,
  PlanningUnitBudgetEntrySchema,
  PlanningUnitConstraintSchema,
  PlanningUnresolvedCriterionSchema,
  PLANNING_DECOMPOSITION_EVENT_TYPES,
  PLANNING_DECOMPOSITION_MAX_BLOCKED_PAIRS,
  PLANNING_DECOMPOSITION_MAX_COVERAGE_OMISSIONS,
  PLANNING_DECOMPOSITION_MAX_CRITERIA,
  PLANNING_DECOMPOSITION_MAX_DEPENDENCIES,
  PLANNING_DECOMPOSITION_MAX_LIST_ITEMS,
  PLANNING_DECOMPOSITION_MAX_SOURCE_SLICES,
  PLANNING_DECOMPOSITION_MAX_SPLIT_ATTEMPTS,
  PLANNING_DECOMPOSITION_MAX_STRING_LENGTH,
  PLANNING_DECOMPOSITION_MAX_UNITS,
  PLANNING_DECOMPOSITION_MAX_UNRESOLVED_CRITERIA,
} from './events/shared/planning-decomposition.js';
export type {
  DecompositionFailureEvidence,
  PlanningCoverageSummary,
  PlanningCriterionCoverage,
  PlanningDecompositionEventType,
  PlanningDecompositionLimits,
  PlanningDecompositionUnitStatus,
  PlanningDecompositionUnitSummary,
  PlanningObservedBudgetPressure,
  PlanningScheduleBlockedPair,
  PlanningScheduleDecision,
  PlanningScheduleWaitingReason,
  PlanningSourceSliceSummary,
  PlanningSplitAttemptEvidence,
  PlanningUnitBudget,
  PlanningUnitBudgetEntry,
  PlanningUnitConstraint,
  PlanningUnresolvedCriterion,
} from './events/shared/planning-decomposition.js';
export { EventEnvelopeSchema } from './events/envelope.js';
export { EforgeEventSchema } from './events/root.js';
export { EforgeEventVariantsSchema } from './events/variants.js';
export { RECOVERY_AUTO_RESUME_MAX_ATTEMPTS } from './events/shared/recovery-auto-resume.js';
export { DaemonStreamSnapshotSchema, SessionStreamSnapshotSchema } from './events/snapshots.js';
export { SEVERITY_ORDER, isAlwaysYieldedAgentEvent, isBuiltInReviewPerspective } from './events/utilities.js';
export { parseEforgeEvent, safeParseDaemonStreamSnapshot, safeParseEforgeEvent, safeParseSessionStreamSnapshot } from './events/parse.js';

export type {
  BoundedDiagnosticOptions,
  BoundedValidationDiagnostic,
  CompileArtifactSummary,
  CompileContextGuardDiagnostics,
  CompileContextGuardLimits,
  CompileContextGuardMetadataSource,
  CompileRecoveryAction,
  CompileScopeContextFailure,
  PlannerContextObservation,
  PlannerInspectionBudgetDiagnostics,
  PlannerInspectionIdentifiers,
  PlannerInspectionOmittedCounts,
  PlannerInspectionSourceBuildContext,
  PlannerInspectionSummary,
} from './events/shared/compile-resilience.js';
export type { BuildDecision, PlanningDecision, PlanningDecisionEvent } from './events/decisions.js';
export type { QueueDispatchFailureStage, QueueEvent } from './events/queue-events.js';
export type { DaemonStreamSnapshot, SessionStreamSnapshot } from './events/snapshots.js';
export type { StackSyncActiveBuildPolicyWire, StackSyncOutcomeWire, StackSyncStatusWire, StackSyncTriggerWire } from './events/shared/stack-wire.js';
export type {
  AcceptanceCriteriaConflict,
  AcceptanceCriterionVerdict,
  AgentResultData,
  AgentRole,
  AgentTerminalSubtype,
  AutoBuildDesired,
  AutoBuildRuntimeMode,
  AutoBuildSchedulerState,
  AutoBuildTransitionDetail,
  BaseSyncEvent,
  BuildFailureSummary,
  BuildResumeArtifactPlan,
  BuildResumeArtifactSource,
  BuildResumeArtifactsEvent,
  BuildResumeCompleteEvent,
  BuildResumeIneligibleEvent,
  CompileScopeContextFailureEvent,
  PlannerInspectionSummaryEvent,
  PlanningDecompositionStartEvent,
  PlanningDecompositionUnitQueuedEvent,
  PlanningDecompositionUnitRunningEvent,
  PlanningDecompositionUnitProgressEvent,
  PlanningDecompositionUnitCompletedEvent,
  PlanningDecompositionUnitSkippedEvent,
  PlanningDecompositionUnitFailedEvent,
  PlanningDecompositionScheduleEvent,
  PlanningDecompositionBudgetEvent,
  PlanningDecompositionCompactHandoffEvent,
  PlanningDecompositionSynthesisCompleteEvent,
  BuildResumeStartEvent,
  BuildResumeStateEvent,
  ClarificationQuestion,
  DaemonRunUpsertEvent,
  EforgeEvent,
  EforgeResult,
  EforgeState,
  EvaluationIssueOutcome,
  FailingPlanEntry,
  LandedCommit,
  LandingAction,
  LandingPublicationAction,
  OrchestrationConfig,
  PipelineComposition,
  PlanFile,
  PlanState,
  PlanSummaryEntry,
  PrdValidationGap,
  ReconciliationReport,
  RecoveryVerdict,
  ReviewFixIssueReference,
  ReviewFixIssueStatus,
  ReviewIssue,
  ReviewIssueId,
  ReviewPerspective,
  ReviewPerspectiveKey,
  ShardScope,
  StackArtifactRef,
  StackLayerStatus,
  StackLayerWire,
  StackProvider,
  StackProviderConflictKind,
  StackProviderOperationKind,
  StalenessVerdict,
  TerminalFailureEnvelope,
  TerminalFailureScope,
  TestIssue,
  ValidationRepairClass,
  EforgeStatus
} from './events/root.js';
