import { Type } from '@sinclair/typebox';
import {
  AcceptanceCriteriaConflictSchema,
  AcceptanceCriterionVerdictSchema,
  AgentResultDataSchema,
  AgentRoleSchema,
  AgentTerminalSubtypeSchema,
  AutoBuildDesiredSchema,
  AutoBuildDetailFields,
  AutoBuildRuntimeModeSchema,
  BuildFailureSummarySchema,
  BuildResumeArtifactsEventSchema,
  BuildStageSpecSchema,
  ClarificationQuestionSchema,
  EforgeResultSchema,
  EvaluationIssueOutcomeSchema,
  FinalMergePolicyGateProvenanceFields,
  LandingActionSchema,
  LandingPublicationActionSchema,
  PlanFileSchema,
  PlanMergePolicyGateProvenanceFields,
  PlanStatusSchema,
  PolicyGateAllowDecisionFields,
  PolicyGateBlockDecisionFields,
  PolicyGateRequireApprovalDecisionFields,
  PrdValidationGapSchema,
  QueueDispatchPolicyGateProvenanceFields,
  ReconciliationReportSchema,
  RecoveryVerdictSchema,
  ReviewCycleRoundField,
  ReviewIssueSchema,
  ReviewPerspectiveKeySchema,
  ReviewProfileConfigSchema,
  StackArtifactRefSchema,
  StackLandingStatusSchema,
  StackProviderConflictKindSchema,
  StackProviderOperationKindSchema,
  StackProviderSchema,
  StackLayerStatusSchema,
  TerminalFailureEnvelopeSchema,
  TestIssueSchema,
} from '../shared/schemas.js';
import { agentStartFields } from '../shared/agent-fields.js';
import {
  ExtensionActionEventBaseFields,
  ExtensionActionFailedErrorCodeSchema,
  ExtensionActionValidationErrorSchema,
  StackSyncTriggerSchema,
} from '../shared/extension-actions.js';
import { BuildDecisionSchema, PlanningDecisionEventSchema } from '../decisions.js';
import { queueEventVariants } from '../queue-events.js';

export const agentEventVariants = [
  // Agent lifecycle
  Type.Object({ type: Type.Literal('agent:start'), ...agentStartFields }),
  Type.Object({
    type: Type.Literal('agent:warning'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    code: Type.String(),
    message: Type.String(),
  }),
  Type.Object({
    type: Type.Literal('agent:stop'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    error: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('agent:usage'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    usage: Type.Object({
      input: Type.Number(),
      output: Type.Number(),
      total: Type.Number(),
      cacheRead: Type.Number(),
      cacheCreation: Type.Number(),
    }),
    costUsd: Type.Number(),
    numTurns: Type.Number(),
    final: Type.Optional(Type.Boolean()),
  }),

  // Agent-level (verbose streaming)
  Type.Object({
    type: Type.Literal('agent:message'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    content: Type.String(),
  }),
  Type.Object({
    type: Type.Literal('agent:tool_use'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    tool: Type.String(),
    toolUseId: Type.String(),
    input: Type.Unknown(),
  }),
  Type.Object({
    type: Type.Literal('agent:tool_result'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    tool: Type.String(),
    toolUseId: Type.String(),
    output: Type.String(),
  }),
  Type.Object({
    type: Type.Literal('agent:result'),
    planId: Type.Optional(Type.String()),
    agentId: Type.Optional(Type.String()),
    agent: AgentRoleSchema,
    result: AgentResultDataSchema,
  }),
  Type.Object({
    type: Type.Literal('agent:activity'),
    planId: Type.Optional(Type.String()),
    agentId: Type.String(),
    agent: AgentRoleSchema,
    files: Type.Optional(Type.Array(Type.Object({
      path: Type.String(),
      status: Type.Optional(Type.String()),
      additions: Type.Optional(Type.Number()),
      deletions: Type.Optional(Type.Number()),
      binary: Type.Optional(Type.Boolean()),
    }))),
    totals: Type.Optional(Type.Object({
      filesChanged: Type.Number(),
      additions: Type.Number(),
      deletions: Type.Number(),
    })),
    attribution: Type.Union([
      Type.Literal('exact'),
      Type.Literal('best_effort'),
      Type.Literal('unavailable'),
    ]),
    notes: Type.Optional(Type.Array(Type.String())),
  }),

  // Generic retry notification
  Type.Object({
    type: Type.Literal('agent:retry'),
    agent: AgentRoleSchema,
    attempt: Type.Number(),
    maxAttempts: Type.Number(),
    subtype: AgentTerminalSubtypeSchema,
    label: Type.String(),
    planId: Type.Optional(Type.String()),
    shardId: Type.Optional(Type.String()),
  }),
] as const;
