import { Type } from '@sinclair/typebox';
import {
  AcceptanceCriteriaConflictSchema,
  AcceptanceCriterionVerdictSchema,
  AgentResultDataSchema,
  AgentRoleSchema,
  AgentTerminalSubtypeSchema,
  AutoBuildDesiredSchema,
  AutoBuildDetailFields,
  AutoBuildRuntimeModeSchema,
  BuildFailureSummarySchema,
  BuildResumeArtifactsEventSchema,
  BuildStageSpecSchema,
  ClarificationQuestionSchema,
  EforgeResultSchema,
  EvaluationIssueOutcomeSchema,
  ExpeditionModuleSchema,
  FinalMergePolicyGateProvenanceFields,
  LandingActionSchema,
  LandingPublicationActionSchema,
  PlanFileSchema,
  PlanMergePolicyGateProvenanceFields,
  PlanStatusSchema,
  PolicyGateAllowDecisionFields,
  PolicyGateBlockDecisionFields,
  PolicyGateRequireApprovalDecisionFields,
  PrdValidationGapSchema,
  QueueDispatchPolicyGateProvenanceFields,
  ReconciliationReportSchema,
  RecoveryVerdictSchema,
  ReviewCycleRoundField,
  ReviewIssueSchema,
  ReviewPerspectiveKeySchema,
  ReviewProfileConfigSchema,
  StackArtifactRefSchema,
  StackLandingStatusSchema,
  StackProviderConflictKindSchema,
  StackProviderOperationKindSchema,
  StackProviderSchema,
  StackLayerStatusSchema,
  TerminalFailureEnvelopeSchema,
  TestIssueSchema,
} from '../shared/schemas.js';
import { agentStartFields } from '../shared/agent-fields.js';
import {
  ExtensionActionEventBaseFields,
  ExtensionActionFailedErrorCodeSchema,
  ExtensionActionValidationErrorSchema,
  StackSyncTriggerSchema,
} from '../shared/extension-actions.js';
import { BuildDecisionSchema, PlanningDecisionEventSchema } from '../decisions.js';
import { queueEventVariants } from '../queue-events.js';

export const extensionEventVariants = [
  // --- eforge:region hook-diagnostics ---
  // Native extension event-hook diagnostics
  Type.Object({
    type: Type.Literal('extension:event-handler:failed'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    pattern: Type.String(),
    triggeringEventType: Type.String(),
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:event-handler:timeout'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    pattern: Type.String(),
    triggeringEventType: Type.String(),
    timeoutMs: Type.Number(),
  }),
  // --- eforge:endregion hook-diagnostics ---

  // --- eforge:region action-events ---
  Type.Object({
    type: Type.Literal('extension:action:start'),
    ...ExtensionActionEventBaseFields,
  }),
  Type.Object({
    type: Type.Literal('extension:action:complete'),
    ...ExtensionActionEventBaseFields,
    durationMs: Type.Number(),
  }),
  Type.Object({
    type: Type.Literal('extension:action:failed'),
    ...ExtensionActionEventBaseFields,
    durationMs: Type.Number(),
    errorCode: ExtensionActionFailedErrorCodeSchema,
    message: Type.String(),
    validationErrors: Type.Optional(Type.Array(ExtensionActionValidationErrorSchema)),
  }),
  Type.Object({
    type: Type.Literal('extension:action:timeout'),
    ...ExtensionActionEventBaseFields,
    durationMs: Type.Number(),
    timeoutMs: Type.Number(),
    message: Type.String(),
  }),
  // --- eforge:endregion action-events ---

  // --- eforge:region agent-context-tool-events ---
  // Native extension agent-context hook diagnostics and tool decisions
  Type.Object({
    type: Type.Literal('extension:agent-context:applied'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    role: AgentRoleSchema,
    tier: Type.Optional(Type.String()),
    phase: Type.Optional(Type.String()),
    stage: Type.Optional(Type.String()),
    profile: Type.String(),
    planId: Type.Optional(Type.String()),
    harness: Type.Optional(Type.Union([Type.Literal('claude-sdk'), Type.Literal('pi')])),
    toolbelt: Type.Optional(Type.Union([Type.String(), Type.Null()])),
    projectMcpSelection: Type.Optional(Type.Union([
      Type.Literal('all'),
      Type.Literal('none'),
      Type.Literal('toolbelt'),
    ])),
    promptCharCount: Type.Integer({ minimum: 0 }),
    fragmentCount: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:agent-context:failed'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    role: AgentRoleSchema,
    tier: Type.Optional(Type.String()),
    phase: Type.Optional(Type.String()),
    stage: Type.Optional(Type.String()),
    profile: Type.String(),
    planId: Type.Optional(Type.String()),
    harness: Type.Optional(Type.Union([Type.Literal('claude-sdk'), Type.Literal('pi')])),
    toolbelt: Type.Optional(Type.Union([Type.String(), Type.Null()])),
    projectMcpSelection: Type.Optional(Type.Union([
      Type.Literal('all'),
      Type.Literal('none'),
      Type.Literal('toolbelt'),
    ])),
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:agent-context:timeout'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    role: AgentRoleSchema,
    tier: Type.Optional(Type.String()),
    phase: Type.Optional(Type.String()),
    stage: Type.Optional(Type.String()),
    profile: Type.String(),
    planId: Type.Optional(Type.String()),
    harness: Type.Optional(Type.Union([Type.Literal('claude-sdk'), Type.Literal('pi')])),
    toolbelt: Type.Optional(Type.Union([Type.String(), Type.Null()])),
    projectMcpSelection: Type.Optional(Type.Union([
      Type.Literal('all'),
      Type.Literal('none'),
      Type.Literal('toolbelt'),
    ])),
    timeoutMs: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:agent-context:unsupported'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    role: AgentRoleSchema,
    tier: Type.Optional(Type.String()),
    phase: Type.Optional(Type.String()),
    stage: Type.Optional(Type.String()),
    profile: Type.String(),
    planId: Type.Optional(Type.String()),
    harness: Type.Optional(Type.Union([Type.Literal('claude-sdk'), Type.Literal('pi')])),
    toolbelt: Type.Optional(Type.Union([Type.String(), Type.Null()])),
    projectMcpSelection: Type.Optional(Type.Union([
      Type.Literal('all'),
      Type.Literal('none'),
      Type.Literal('toolbelt'),
    ])),
    fields: Type.Array(Type.Union([
      Type.Literal('tools'),
      Type.Literal('allowedTools'),
      Type.Literal('disallowedTools'),
    ]), { minItems: 1 }),
  }),
  Type.Object({
    type: Type.Literal('extension:agent-tools:applied'),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    role: AgentRoleSchema,
    tier: Type.Optional(Type.String()),
    phase: Type.Optional(Type.String()),
    stage: Type.Optional(Type.String()),
    profile: Type.String(),
    planId: Type.Optional(Type.String()),
    harness: Type.Optional(Type.Union([Type.Literal('claude-sdk'), Type.Literal('pi')])),
    toolbelt: Type.Optional(Type.Union([Type.String(), Type.Null()])),
    projectMcpSelection: Type.Optional(Type.Union([
      Type.Literal('all'),
      Type.Literal('none'),
      Type.Literal('toolbelt'),
    ])),
    projectMcpServerNames: Type.Optional(Type.Array(Type.String())),
    toolNames: Type.Array(Type.String()),
    effectiveToolNames: Type.Array(Type.String()),
    registeredToolNames: Type.Array(Type.String()),
    inlineToolNames: Type.Array(Type.String()),
    allowedToolsAdded: Type.Array(Type.String()),
    disallowedToolsAdded: Type.Array(Type.String()),
    excludedToolNames: Type.Array(Type.String()),
    toolCount: Type.Integer({ minimum: 0 }),
    allowedToolCount: Type.Integer({ minimum: 0 }),
    disallowedToolCount: Type.Integer({ minimum: 0 }),
    excludedToolCount: Type.Integer({ minimum: 0 }),
  }),
  // --- eforge:endregion agent-context-tool-events ---

  // --- eforge:region profile-router-events ---
  // Profile router dispatch diagnostics (EXTEND_09)
  Type.Object({
    type: Type.Literal('queue:profile:selected'),
    prdId: Type.String(),
    prdTitle: Type.Optional(Type.String()),
    profile: Type.String(),
    baseProfile: Type.Union([Type.String(), Type.Null()]),
    routerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    reason: Type.Optional(Type.String()),
    confidence: Type.Optional(Type.Union([
      Type.Literal('low'),
      Type.Literal('medium'),
      Type.Literal('high'),
    ])),
  }),
  Type.Object({
    type: Type.Literal('queue:profile:router-failed'),
    prdId: Type.String(),
    routerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('queue:profile:router-timeout'),
    prdId: Type.String(),
    routerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    timeoutMs: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('queue:profile:invalid-selection'),
    prdId: Type.String(),
    routerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    requestedProfile: Type.String(),
    reason: Type.Union([Type.Literal('not-found'), Type.Literal('load-error')]),
    message: Type.String(),
  }),
  // --- eforge:endregion profile-router-events ---

  // --- eforge:region policy-gates ---
  // Blocking policy-gate decisions and diagnostics. Keep these as top-level
  // variants so generated event documentation lists each public wire shape.
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...QueueDispatchPolicyGateProvenanceFields,
    ...PolicyGateAllowDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...QueueDispatchPolicyGateProvenanceFields,
    ...PolicyGateBlockDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...QueueDispatchPolicyGateProvenanceFields,
    ...PolicyGateRequireApprovalDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...PlanMergePolicyGateProvenanceFields,
    ...PolicyGateAllowDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...PlanMergePolicyGateProvenanceFields,
    ...PolicyGateBlockDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...PlanMergePolicyGateProvenanceFields,
    ...PolicyGateRequireApprovalDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...FinalMergePolicyGateProvenanceFields,
    ...PolicyGateAllowDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...FinalMergePolicyGateProvenanceFields,
    ...PolicyGateBlockDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:decision'),
    ...FinalMergePolicyGateProvenanceFields,
    ...PolicyGateRequireApprovalDecisionFields,
  }),
  Type.Object({
    type: Type.Literal('extension:policy:failed'),
    ...QueueDispatchPolicyGateProvenanceFields,
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:policy:failed'),
    ...PlanMergePolicyGateProvenanceFields,
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:policy:failed'),
    ...FinalMergePolicyGateProvenanceFields,
    message: Type.String(),
    stack: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:policy:timeout'),
    ...QueueDispatchPolicyGateProvenanceFields,
    timeoutMs: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:policy:timeout'),
    ...PlanMergePolicyGateProvenanceFields,
    timeoutMs: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:policy:timeout'),
    ...FinalMergePolicyGateProvenanceFields,
    timeoutMs: Type.Integer({ minimum: 0 }),
  }),
  // --- eforge:endregion policy-gates ---

  // --- eforge:region input-prd-enrichment ---
  // Input source and PRD enricher provenance/diagnostic events
  Type.Object({
    type: Type.Literal('extension:input-source:fetched'),
    extensionPath: Type.String(),
    extensionName: Type.String(),
    adapterName: Type.String(),
    sourceId: Type.String(),
    contentLength: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:input-source:failed'),
    extensionPath: Type.String(),
    extensionName: Type.String(),
    adapterName: Type.String(),
    sourceId: Type.String(),
    reason: Type.Union([
      Type.Literal('not-found'),
      Type.Literal('error'),
      Type.Literal('timeout'),
      Type.Literal('invalid-result'),
    ]),
    message: Type.String(),
    stack: Type.Optional(Type.String()),
    timeoutMs: Type.Optional(Type.Integer({ minimum: 0 })),
  }),
  Type.Object({
    type: Type.Literal('extension:prd-enricher:applied'),
    extensionPath: Type.String(),
    extensionName: Type.String(),
    enricherName: Type.String(),
    sourceId: Type.String(),
    changed: Type.Boolean(),
    inputLength: Type.Integer({ minimum: 0 }),
    outputLength: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('extension:prd-enricher:failed'),
    extensionPath: Type.String(),
    extensionName: Type.String(),
    enricherName: Type.String(),
    sourceId: Type.String(),
    reason: Type.Union([
      Type.Literal('error'),
      Type.Literal('timeout'),
      Type.Literal('invalid-result'),
    ]),
    message: Type.String(),
    stack: Type.Optional(Type.String()),
    timeoutMs: Type.Optional(Type.Integer({ minimum: 0 })),
  }),
  // --- eforge:endregion input-prd-enrichment ---

  // --- eforge:region reviewer-perspectives ---
  // Extension reviewer perspective provenance/diagnostic events
  Type.Object({
    type: Type.Literal('extension:reviewer-perspective:applied'),
    extensionPath: Type.String(),
    extensionName: Type.String(),
    perspectiveKey: ReviewPerspectiveKeySchema,
    perspectiveLabel: Type.String(),
    planId: Type.Optional(Type.String()),
  }),
  Type.Union([
    Type.Object({
      type: Type.Literal('extension:reviewer-perspective:skipped'),
      extensionPath: Type.String(),
      extensionName: Type.String(),
      perspectiveKey: ReviewPerspectiveKeySchema,
      reason: Type.Union([
        Type.Literal('not-applicable'),
        Type.Literal('applicability-error'),
        Type.Literal('applicability-timeout'),
      ]),
      message: Type.Optional(Type.String()),
      planId: Type.Optional(Type.String()),
      timeoutMs: Type.Optional(Type.Integer({ minimum: 0 })),
    }),
    Type.Object({
      type: Type.Literal('extension:reviewer-perspective:skipped'),
      extensionPath: Type.Optional(Type.String()),
      extensionName: Type.Optional(Type.String()),
      perspectiveKey: ReviewPerspectiveKeySchema,
      reason: Type.Literal('unknown-key'),
      message: Type.Optional(Type.String()),
      planId: Type.Optional(Type.String()),
    }),
  ]),
  // --- eforge:endregion reviewer-perspectives ---

  // --- eforge:region validation-provider-events ---
  // Extension validation provider lifecycle events
  Type.Object({
    type: Type.Literal('extension:validation-provider:start'),
    planId: Type.String(),
    providerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    kind: Type.Union([Type.Literal('validate'), Type.Literal('commands')]),
    commandCount: Type.Optional(Type.Integer({ minimum: 0 })),
  }),
  Type.Object({
    type: Type.Literal('extension:validation-provider:complete'),
    planId: Type.String(),
    providerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    status: Type.Union([Type.Literal('passed'), Type.Literal('skipped')]),
    message: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('extension:validation-provider:error'),
    planId: Type.String(),
    providerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    status: Type.Literal('failed'),
    message: Type.String(),
    details: Type.Optional(Type.String()),
    command: Type.Optional(Type.String()),
    exitCode: Type.Optional(Type.Integer()),
  }),
  Type.Object({
    type: Type.Literal('extension:validation-provider:timeout'),
    planId: Type.String(),
    providerName: Type.String(),
    extensionName: Type.String(),
    extensionPath: Type.String(),
    timeoutMs: Type.Integer({ minimum: 0 }),
    command: Type.Optional(Type.String()),
  }),
  // --- eforge:endregion validation-provider-events ---
] as const;
