import { Type } from '@sinclair/typebox';
import {
  AcceptanceCriteriaConflictSchema,
  AcceptanceCriterionVerdictSchema,
  AgentResultDataSchema,
  AgentRoleSchema,
  AgentTerminalSubtypeSchema,
  AutoBuildDesiredSchema,
  AutoBuildDetailFields,
  AutoBuildRuntimeModeSchema,
  BuildFailureSummarySchema,
  BuildResumeArtifactsEventSchema,
  BuildStageSpecSchema,
  ClarificationQuestionSchema,
  EforgeResultSchema,
  EvaluationIssueOutcomeSchema,
  FinalMergePolicyGateProvenanceFields,
  LandingActionSchema,
  LandingPublicationActionSchema,
  PlanFileSchema,
  PlanMergePolicyGateProvenanceFields,
  PlanStatusSchema,
  PolicyGateAllowDecisionFields,
  PolicyGateBlockDecisionFields,
  PolicyGateRequireApprovalDecisionFields,
  PrdValidationGapSchema,
  QueueDispatchPolicyGateProvenanceFields,
  ReconciliationReportSchema,
  RecoveryVerdictSchema,
  ReviewCycleRoundField,
  ReviewIssueSchema,
  ReviewPerspectiveKeySchema,
  ReviewProfileConfigSchema,
  StackArtifactRefSchema,
  StackLandingStatusSchema,
  StackProviderConflictKindSchema,
  StackProviderOperationKindSchema,
  StackProviderSchema,
  StackLayerStatusSchema,
  TerminalFailureEnvelopeSchema,
  TestIssueSchema,
} from '../shared/schemas.js';
import { agentStartFields } from '../shared/agent-fields.js';
import {
  ExtensionActionEventBaseFields,
  ExtensionActionFailedErrorCodeSchema,
  ExtensionActionValidationErrorSchema,
  StackSyncTriggerSchema,
} from '../shared/extension-actions.js';
import { BuildDecisionSchema, PlanningDecisionEventSchema } from '../decisions.js';
import { queueEventVariants } from '../queue-events.js';

export const stackEventVariants = [
  // Stack layer lifecycle and provider command events
  Type.Object({
    type: Type.Literal('stack:layer:recorded'),
    prdId: Type.String(),
    stackId: Type.String(),
    parentPrdId: Type.Optional(Type.String()),
    provider: StackProviderSchema,
    branch: Type.String(),
    baseBranch: Type.Optional(Type.String()),
    artifact: Type.Optional(StackArtifactRefSchema),
    landingAction: Type.Optional(LandingPublicationActionSchema),
    status: StackLayerStatusSchema,
  }),
  Type.Object({
    type: Type.Literal('stack:provider:command'),
    provider: StackProviderSchema,
    command: Type.String(),
    args: Type.Optional(Type.Array(Type.String())),
    exitCode: Type.Union([Type.Integer(), Type.Null()]),
    branch: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('stack:landing:update'),
    prdId: Type.String(),
    stackId: Type.String(),
    action: LandingPublicationActionSchema,
    branch: Type.String(),
    status: StackLandingStatusSchema,
    prUrl: Type.Optional(Type.String()),
    reason: Type.Optional(Type.String()),
    originalBaseBranch: Type.Optional(Type.String()),
    effectiveBaseBranch: Type.Optional(Type.String()),
    baseRepairReason: Type.Optional(Type.Literal('parent-artifact-already-integrated')),
  }),
  Type.Object({
    type: Type.Literal('stack:landing:conflict:detected'),
    prdId: Type.String(),
    stackId: Type.String(),
    provider: StackProviderSchema,
    branch: Type.String(),
    operation: StackProviderOperationKindSchema,
    conflictKind: StackProviderConflictKindSchema,
    conflictedFiles: Type.Array(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('stack:landing:conflict:recovery:start'),
    prdId: Type.String(),
    stackId: Type.String(),
    provider: StackProviderSchema,
    branch: Type.String(),
    attempt: Type.Integer({ minimum: 1 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
  }),
  Type.Object({
    type: Type.Literal('stack:landing:conflict:recovery:complete'),
    prdId: Type.String(),
    stackId: Type.String(),
    provider: StackProviderSchema,
    branch: Type.String(),
    attempts: Type.Integer({ minimum: 1 }),
  }),
  Type.Object({
    type: Type.Literal('stack:landing:conflict:recovery:failed'),
    prdId: Type.String(),
    stackId: Type.String(),
    provider: StackProviderSchema,
    branch: Type.String(),
    attempts: Type.Integer({ minimum: 0 }),
    reason: Type.String(),
    abortAttempted: Type.Boolean(),
    abortSucceeded: Type.Boolean(),
  }),
  Type.Object({
    type: Type.Literal('stack:sync:start'),
    syncId: Type.String(),
    trigger: StackSyncTriggerSchema,
    dryRun: Type.Boolean(),
  }),
  Type.Object({
    type: Type.Literal('stack:sync:complete'),
    syncId: Type.String(),
    trigger: StackSyncTriggerSchema,
    dryRun: Type.Boolean(),
    restackCandidates: Type.Array(Type.String()),
    excludedCandidates: Type.Array(Type.String()),
    localTrunkSha: Type.Optional(Type.String()),
    originTrunkSha: Type.Optional(Type.String()),
    fastForward: Type.Optional(Type.Boolean()),
    reason: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('stack:sync:failed'),
    syncId: Type.String(),
    trigger: StackSyncTriggerSchema,
    dryRun: Type.Boolean(),
    outcome: Type.Union([Type.Literal('failed'), Type.Literal('conflict')]),
    reason: Type.String(),
    error: Type.Optional(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('stack:sync:deferred'),
    syncId: Type.String(),
    trigger: StackSyncTriggerSchema,
    reason: Type.String(),
    excludedCandidates: Type.Array(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('stack:sync:skipped'),
    syncId: Type.String(),
    trigger: StackSyncTriggerSchema,
    dryRun: Type.Boolean(),
    reason: Type.String(),
    restackCandidates: Type.Array(Type.String()),
    excludedCandidates: Type.Array(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('base-sync:start'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    maxAttempts: Type.Integer({ minimum: 1 }),
  }),
  Type.Object({
    type: Type.Literal('base-sync:conflict:attempt'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    attempt: Type.Integer({ minimum: 1 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
    conflictedFiles: Type.Array(Type.String()),
  }),
  Type.Object({
    type: Type.Literal('base-sync:resolver:start'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    attempt: Type.Integer({ minimum: 1 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
  }),
  Type.Object({
    type: Type.Literal('base-sync:resolver:complete'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    attempt: Type.Integer({ minimum: 1 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
    resolved: Type.Boolean(),
    remainingConflicts: Type.Integer({ minimum: 0 }),
  }),
  Type.Object({
    type: Type.Literal('base-sync:rebase:continue'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    attempt: Type.Integer({ minimum: 1 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
  }),
  Type.Object({
    type: Type.Literal('base-sync:success'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    baseSha: Type.String(),
    featureSha: Type.String(),
    rebased: Type.Boolean(),
  }),
  Type.Object({
    type: Type.Literal('base-sync:budget:exhausted'),
    remote: Type.String(),
    baseBranch: Type.String(),
    featureBranch: Type.String(),
    attempts: Type.Integer({ minimum: 0 }),
    maxAttempts: Type.Integer({ minimum: 1 }),
    conflictedFiles: Type.Array(Type.String()),
  }),
] as const;
