import { CONTRIBUTION_OUTPUT_PROFILES, Type, defineExtensionAction, type Static } from '@eforge-build/extension-sdk';
import { toJsonSafeObject } from '../json-safe.js';
import { SearchIndexStatusSchema } from '../search/schemas.js';
import { compactPlanningStore } from './compact.js';
import { getPlanningStoreStatus } from './status.js';
import { rebuildPlanningSearchIndex, optimizePlanningSearchIndex } from './search-actions.js';
import { vacuumPlanningStore } from './sqlite-maintenance.js';

const MaintenanceCategorySchema = Type.Union([
  Type.Literal('lifecycle-event-payloads'), Type.Literal('planning-task-payloads'), Type.Literal('superseded-recommendation-runs'), Type.Literal('import-report-payloads'), Type.Literal('import-diagnostic-details'),
]);
const SearchDocumentTypeSchema = Type.Union([Type.Literal('backlog_item'), Type.Literal('epic'), Type.Literal('session_plan'), Type.Literal('recommendation')]);
export const GetStoreStatusInputSchema = Type.Object({ recentRunLimit: Type.Optional(Type.Integer({ minimum: 0, maximum: 100 })) }, { additionalProperties: false });
export const CompactPlanningStoreInputSchema = Type.Object({ dryRun: Type.Optional(Type.Boolean()), categories: Type.Optional(Type.Array(MaintenanceCategorySchema, { minItems: 1, uniqueItems: true })), olderThan: Type.Optional(Type.String({ format: 'date-time' })), olderThanDays: Type.Optional(Type.Integer({ minimum: 0 })), archive: Type.Optional(Type.Boolean()), rowLimit: Type.Optional(Type.Integer({ minimum: 1, maximum: 50000 })), sampleLimit: Type.Optional(Type.Integer({ minimum: 0, maximum: 500 })), keepLatestRecommendationRuns: Type.Optional(Type.Integer({ minimum: 0 })), keepLatestImportRuns: Type.Optional(Type.Integer({ minimum: 0 })), rebuildSearchAfter: Type.Optional(Type.Boolean()) }, { additionalProperties: false });
export const RebuildSearchIndexInputSchema = Type.Object({ types: Type.Optional(Type.Array(SearchDocumentTypeSchema, { minItems: 1, uniqueItems: true })), reason: Type.Optional(Type.String()) }, { additionalProperties: false });
export const VacuumPlanningStoreInputSchema = Type.Object({ checkpointWal: Type.Optional(Type.Boolean()) }, { additionalProperties: false });

const CountRecordSchema = Type.Record(Type.String(), Type.Integer({ minimum: 0 }));
const MaintenanceRunSummarySchema = Type.Object({ runId: Type.String(), categories: Type.Optional(Type.Array(Type.String(), { maxItems: 20 })), startedAt: Type.Optional(Type.String()), finishedAt: Type.Optional(Type.String()), status: Type.Optional(Type.String()), prunedCounts: Type.Optional(CountRecordSchema), archivedCounts: Type.Optional(CountRecordSchema), preservedEvidenceCounts: Type.Optional(CountRecordSchema), errorSummary: Type.Optional(Type.String({ maxLength: 1000 })) }, { additionalProperties: false });
const MaintenanceSampleSchema = Type.Object({ eventKey: Type.Optional(Type.String()), eventType: Type.Optional(Type.String()), taskId: Type.Optional(Type.String()), purpose: Type.Optional(Type.String()), status: Type.Optional(Type.String()), runId: Type.Optional(Type.String()), diagnosticId: Type.Optional(Type.String()), isCurrent: Type.Optional(Type.Boolean()), occurredAt: Type.Optional(Type.String()), updatedAt: Type.Optional(Type.String()), createdAt: Type.Optional(Type.String()), summary: Type.Optional(Type.String()), laneCount: Type.Optional(Type.Integer({ minimum: 0 })), laneItemCount: Type.Optional(Type.Integer({ minimum: 0 })), hasRawRequest: Type.Optional(Type.Boolean()), hasRawResult: Type.Optional(Type.Boolean()) }, { additionalProperties: false });
const SearchRefreshReportSchema = Type.Object({ refreshed: Type.Integer({ minimum: 0 }), deleted: Type.Integer({ minimum: 0 }), clearedDirty: Type.Integer({ minimum: 0 }), types: Type.Optional(Type.Array(SearchDocumentTypeSchema)), reason: Type.Optional(Type.String()), rebuiltAt: Type.Optional(Type.String()) }, { additionalProperties: true });
export const MaintenanceReportOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), runId: Type.String(), status: Type.Union([Type.Literal('dry-run'), Type.Literal('applied'), Type.Literal('failed')]), dryRun: Type.Boolean(), categories: Type.Array(MaintenanceCategorySchema), cutoff: Type.String(), archive: Type.Boolean(), rowLimit: Type.Integer({ minimum: 1 }), sampleLimit: Type.Integer({ minimum: 0 }), prunedCounts: CountRecordSchema, archivedCounts: CountRecordSchema, preservedEvidenceCounts: CountRecordSchema, archivePaths: Type.Array(Type.Object({ category: MaintenanceCategorySchema, path: Type.String(), rowCount: Type.Integer({ minimum: 0 }) }, { additionalProperties: false })), samples: Type.Partial(Type.Record(MaintenanceCategorySchema, Type.Array(MaintenanceSampleSchema))), searchRefresh: Type.Optional(SearchRefreshReportSchema), warnings: Type.Array(Type.String()) }, { additionalProperties: false });
export const PlanningStoreStatusOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), initialized: Type.Boolean(), storePath: Type.String(), fileSizes: Type.Object({ dbBytes: Type.Integer({ minimum: 0 }), walBytes: Type.Integer({ minimum: 0 }), shmBytes: Type.Integer({ minimum: 0 }) }, { additionalProperties: false }), sqliteSchemaVersion: Type.Optional(Type.Integer()), tableCounts: Type.Array(Type.Object({ table: Type.String(), count: Type.Integer({ minimum: 0 }) }, { additionalProperties: false })), retentionEligibilityCounts: CountRecordSchema, searchIndexStatus: Type.Optional(SearchIndexStatusSchema), recentMaintenanceRuns: Type.Array(MaintenanceRunSummarySchema) }, { additionalProperties: false });
export const SearchIndexMaintenanceActionReportOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), runId: Type.String(), category: Type.Union([Type.Literal('search-rebuild'), Type.Literal('search-optimize')]), status: Type.Union([Type.Literal('applied'), Type.Literal('failed')]), searchRefresh: Type.Optional(SearchRefreshReportSchema), optimizedAt: Type.Optional(Type.String()), ok: Type.Optional(Type.Boolean()) }, { additionalProperties: false });
export const VacuumStoreReportOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), runId: Type.String(), status: Type.Union([Type.Literal('applied'), Type.Literal('failed')]), beforeBytes: Type.Integer({ minimum: 0 }), afterBytes: Type.Integer({ minimum: 0 }), walBytesBefore: Type.Integer({ minimum: 0 }), walBytesAfter: Type.Integer({ minimum: 0 }), shmBytesBefore: Type.Integer({ minimum: 0 }), shmBytesAfter: Type.Integer({ minimum: 0 }), checkpoint: Type.Optional(Type.Object({ requested: Type.Boolean(), walBytesBefore: Type.Integer({ minimum: 0 }), walBytesAfter: Type.Integer({ minimum: 0 }) }, { additionalProperties: false })) }, { additionalProperties: false });

export const getStoreStatusAction = defineExtensionAction({ id: 'get-store-status', title: 'Get eforge-plan store status', description: 'Report SQLite store size, schema, retention eligibility, search freshness, and recent maintenance runs without creating a store.', inputSchema: GetStoreStatusInputSchema, outputSchema: PlanningStoreStatusOutputSchema, outputProfile: CONTRIBUTION_OUTPUT_PROFILES.agentCompact, sideEffects: ['local-read'], async handler(input: Static<typeof GetStoreStatusInputSchema>, ctx) { return toJsonSafeObject(await getPlanningStoreStatus(ctx.cwd, input)) as never; } });
export const compactPlanningStoreAction = defineExtensionAction({ id: 'compact-planning-store', title: 'Compact eforge-plan store', description: 'Dry-run-first explicit retention compaction for prunable raw payloads, reports, diagnostics, and superseded recommendation runs.', inputSchema: CompactPlanningStoreInputSchema, outputSchema: MaintenanceReportOutputSchema, outputProfile: CONTRIBUTION_OUTPUT_PROFILES.agentCompact, sideEffects: ['local-write'], async handler(input: Static<typeof CompactPlanningStoreInputSchema>, ctx) { return toJsonSafeObject(await compactPlanningStore(ctx.cwd, input)) as never; } });
export const rebuildSearchIndexAction = defineExtensionAction({ id: 'rebuild-search-index', title: 'Rebuild eforge-plan search index', description: 'Explicitly rebuild requested SQLite FTS search document types and clear matching dirty markers.', inputSchema: RebuildSearchIndexInputSchema, outputSchema: SearchIndexMaintenanceActionReportOutputSchema, outputProfile: CONTRIBUTION_OUTPUT_PROFILES.agentCompact, sideEffects: ['local-write'], async handler(input: Static<typeof RebuildSearchIndexInputSchema>, ctx) { return toJsonSafeObject(await rebuildPlanningSearchIndex(ctx.cwd, input)) as never; } });
export const optimizeSearchIndexAction = defineExtensionAction({ id: 'optimize-search-index', title: 'Optimize eforge-plan search index', description: 'Run explicit SQLite FTS optimize maintenance and record an observable maintenance run.', inputSchema: Type.Object({}, { additionalProperties: false }), outputSchema: SearchIndexMaintenanceActionReportOutputSchema, outputProfile: CONTRIBUTION_OUTPUT_PROFILES.agentCompact, sideEffects: ['local-write'], async handler(_input, ctx) { return toJsonSafeObject(await optimizePlanningSearchIndex(ctx.cwd)) as never; } });
export const vacuumPlanningStoreAction = defineExtensionAction({ id: 'vacuum-planning-store', title: 'VACUUM eforge-plan store', description: 'Run explicit SQLite WAL checkpoint/VACUUM maintenance with before/after byte counts.', inputSchema: VacuumPlanningStoreInputSchema, outputSchema: VacuumStoreReportOutputSchema, outputProfile: CONTRIBUTION_OUTPUT_PROFILES.agentCompact, sideEffects: ['local-write'], async handler(input: Static<typeof VacuumPlanningStoreInputSchema>, ctx) { return toJsonSafeObject(await vacuumPlanningStore(ctx.cwd, input)) as never; } });

export const maintenanceActions = [getStoreStatusAction, compactPlanningStoreAction, rebuildSearchIndexAction, optimizeSearchIndexAction, vacuumPlanningStoreAction] as const;
