import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { LifecycleState } from '../sqlite/types.js';
import type { Collector } from './types.js';
import { addDiagnostic } from './diagnostics.js';
import { asString, compactText, projectRelative, sha256, stableId } from './stable.js';

export const collectLegacyTraces: Collector = (cwd, graph) => {
  if (!graph.include.includes('traces')) return;
  const root = join(cwd, '.eforge/storage/extensions/eforge-plan/traces'); if (!existsSync(root)) return;
  for (const name of readdirSync(root).filter((n) => n.endsWith('.json')).sort()) {
    const path = join(root, name); const rel = projectRelative(cwd, path);
    let raw: unknown; try { raw = JSON.parse(readFileSync(path, 'utf8')); } catch (e) { addDiagnostic(graph, 'invalid-trace-row', `Malformed trace JSON ${name}.`, { path: rel, severity: 'error', details: { error: String(e) } }); continue; }
    if (!raw || typeof raw !== 'object') { addDiagnostic(graph, 'invalid-trace-row', `Trace ${name} is not an object.`, { path: rel, severity: 'error' }); continue; }
    const t = raw as Record<string, unknown>; const itemId = asString(t.itemId) ?? asString(t.item_id) ?? name.replace(/\.json$/, '');
    const sessions = array(t.promotedPlans ?? t.promotedSessionPlans ?? t.sessionPlans);
    for (const [i, p] of sessions.entries()) {
      const o = object(p); const session = asString(o.session) ?? asString(o.sessionId) ?? asString(o.id) ?? `trace-${itemId}-${i}`;
      if (!graph.sessionPlans.some((s) => s.plan.session === session)) { graph.sessionPlans.push({ plan: { session, path: asString(o.path), status: asString(o.status), summaryText: compactText(o.summary), frontmatter: {}, importOrigin: 'trace-sidecar', importPath: rel }, itemLinks: [{ itemRef: itemId, itemId: knownItem(graph, itemId), role: 'source', provenance: 'imported-trace' }], epicLinks: [] }); addDiagnostic(graph, 'missing-file', `Trace references session plan ${session} without a Markdown artifact.`, { ref: session, path: rel }); }
    }
    for (const [i, q] of array(t.queuePrds ?? t.queue ?? t.queuePrdRefs).entries()) { const o = object(q); const prdId = asString(o.prdId) ?? asString(o.id) ?? `${itemId}-queue-${i}`; const session = knownSession(graph, asString(o.session)); graph.queuePrds.push({ prdId, session, sourcePath: rel, status: asString(o.status), submittedAt: asString(o.submittedAt), statusSummary: compactText(o.summary), importFingerprint: sha256(JSON.stringify(o)) }); evidence(graph, `trace:${itemId}:queue:${prdId}`, itemId, state(o.status) ?? 'queued', rel, { queuePrdId: prdId, status: asString(o.status), summary: compactText(o.summary) }); }
    for (const [i, r] of array(t.buildRuns ?? t.runs).entries()) { const o = object(r); const runId = asString(o.runId) ?? asString(o.id) ?? `${itemId}-run-${i}`; const queuePrdId = knownQueuePrd(graph, asString(o.prdId)); graph.buildRuns.push({ runId, session: knownSession(graph, asString(o.session)), queuePrdId, buildSessionId: asString(o.buildSessionId) ?? asString(o.sessionId), status: asString(o.status), startedAt: asString(o.startedAt), finishedAt: asString(o.finishedAt), statusSummary: compactText(o.summary), importFingerprint: sha256(JSON.stringify(o)) }); if (asString(o.prdId) && !queuePrdId) addDiagnostic(graph, 'orphan-ref', `Trace build run ${runId} references missing queue PRD ${asString(o.prdId)}.`, { ref: asString(o.prdId), path: rel }); }
    for (const [i, s] of array(t.buildSessions ?? t.sessions).entries()) { const o = object(s); const buildSessionId = asString(o.buildSessionId) ?? asString(o.sessionId) ?? asString(o.id) ?? `${itemId}-build-session-${i}`; graph.buildSessions.push({ buildSessionId, session: knownSession(graph, asString(o.session)), status: asString(o.status), startedAt: asString(o.startedAt), finishedAt: asString(o.finishedAt), statusSummary: compactText(o.summary), importFingerprint: sha256(JSON.stringify(o)) }); evidence(graph, `trace:${itemId}:build-session:${buildSessionId}`, itemId, state(o.status) ?? 'build', rel, { buildSessionId, status: asString(o.status) }); }
    for (const [i, l] of array(t.landingResults ?? t.landings).entries()) { const o = object(l); const landingId = stableId('trace-landing', { itemId, i, o }); graph.landingLinks.push({ landingId, itemId: knownItem(graph, itemId), session: knownSession(graph, asString(o.session)), queuePrdId: knownQueuePrd(graph, asString(o.prdId) ?? asString(o.queuePrdId)), runId: knownRun(graph, asString(o.runId)), buildSessionId: knownBuildSession(graph, asString(o.buildSessionId) ?? asString(o.sessionId)), status: asString(o.status), prUrl: asString(o.prUrl), featureBranch: asString(o.featureBranch), commitSha: asString(o.commitSha), completedAt: asString(o.landedAt) ?? asString(o.completedAt), summary: o as never }); evidence(graph, `trace:${itemId}:landing:${landingId}`, itemId, state(o.status) ?? 'pr-open', rel, { landingId, status: asString(o.status), links: o }); }
    const last = object(t.lastEvent); if (Object.keys(last).length) graph.lifecycleEvents.push({ eventKey: `trace:${itemId}:last-event:${sha256(JSON.stringify(last)).slice(0, 16)}`, eventType: asString(last.type) ?? 'trace:last-event', timestamp: asString(last.timestamp), session: asString(last.sessionId), runId: asString(last.runId), affectedItemRefs: [itemId], payload: last as never, sourceFingerprint: sha256(JSON.stringify(last)) });
  }
};
function array(v: unknown): unknown[] { return Array.isArray(v) ? v : []; } function object(v: unknown): Record<string, unknown> { return v && typeof v === 'object' ? v as Record<string, unknown> : {}; }
function knownItem(graph: Parameters<Collector>[1], id: string): string | undefined { return graph.items.some((i) => i.item.id === id) ? id : undefined; }
function knownSession(graph: Parameters<Collector>[1], id: string | undefined): string | undefined { return id && graph.sessionPlans.some((s) => s.plan.session === id) ? id : undefined; }
function knownQueuePrd(graph: Parameters<Collector>[1], id: string | undefined): string | undefined { return id && graph.queuePrds.some((q) => q.prdId === id) ? id : undefined; }
function knownRun(graph: Parameters<Collector>[1], id: string | undefined): string | undefined { return id && graph.buildRuns.some((r) => r.runId === id) ? id : undefined; }
function knownBuildSession(graph: Parameters<Collector>[1], id: string | undefined): string | undefined { return id && graph.buildSessions.some((s) => s.buildSessionId === id) ? id : undefined; }
function state(s: unknown): LifecycleState | undefined { const v = String(s ?? ''); if (['shipped','merged','failed','partial','planned','submitted','queued','build'].includes(v)) return v as LifecycleState; if (v === 'pr-open' || v === 'landed') return v === 'landed' ? 'shipped' : 'pr-open'; return undefined; }
function evidence(graph: Parameters<Collector>[1], evidenceKey: string, itemRef: string, lifecycleState: LifecycleState, path: string, extra: Record<string, unknown>) { graph.lifecycleEvidence.push({ evidenceKey, itemRef, itemId: knownItem(graph, itemRef), lifecycleState, reasonCode: 'imported-trace', evidenceKind: 'trace', status: asString(extra.status), summary: compactText(extra.summary), links: { path, ...extra } as never }); }
