/**
 * Deterministic recovery recommendation module.
 *
 * Turns BuildFailureSummary facts into a conservative RecoveryVerdict candidate
 * without calling any AI agents. The recommendation is used as a fallback when
 * the analyst fails or produces invalid output, and is included in the analyst
 * prompt as evidence.
 *
 * Exported helpers are used by both recovery entry points in eforge.ts.
 */

import type { BuildFailureSummary, RecoveryVerdict } from '../events.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RecoveryRecommendation {
  verdict: 'retry' | 'split' | 'manual';
  rationale: string;
}

export interface ValidateAnalystVerdictResult {
  valid: boolean;
  invalidationReason?: string;
}

export interface SelectFinalVerdictOptions {
  deterministicRecommendation: RecoveryRecommendation;
  analystVerdict: RecoveryVerdict | null;
  analystError?: string;
  parseError?: string;
  summary: BuildFailureSummary;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Subtypes that are classified as transient transport failures. */
const TRANSIENT_SUBTYPES = new Set(['error_transient_transport']);

function isTransientSubtype(terminalSubtype: string | null | undefined): boolean {
  return typeof terminalSubtype === 'string' && TRANSIENT_SUBTYPES.has(terminalSubtype);
}

function hasCompletedOrMergedPlans(summary: BuildFailureSummary): boolean {
  if (summary.plans.some(p => p.status === 'completed' || p.status === 'merged')) {
    return true;
  }
  // Also treat non-empty landedCommits or non-empty diffStat as evidence of preserved work
  if (summary.landedCommits && summary.landedCommits.length > 0) {
    return true;
  }
  if (typeof summary.diffStat === 'string' && summary.diffStat.trim().length > 0) {
    return true;
  }
  return false;
}

/**
 * Synthesize a minimal placeholder `suggestedSuccessorPrd` for use in deterministic
 * split verdicts that have no analyst-generated successor. The placeholder covers all
 * failed plan IDs from `failingPlans` plus any remaining non-completed/non-merged plans.
 */
function synthesizeSplitSuccessorPrd(
  summary: BuildFailureSummary,
  deterministicRationale: string,
): string {
  const failedIds = (summary.failingPlans ?? []).map(p => p.planId);
  const remainingIds = summary.plans
    .filter(p => p.status !== 'completed' && p.status !== 'merged')
    .map(p => p.planId)
    .filter(id => !failedIds.includes(id));
  const allIds = [...new Set([...failedIds, ...remainingIds])];
  const idList = allIds.length > 0
    ? allIds.map(id => `- ${id}`).join('\n')
    : '- (unknown — review the original failed PRD for plan details)';
  return [
    '# Successor PRD',
    '',
    '<!-- Auto-generated by deterministic fallback policy. Review and refine before applying. -->',
    '',
    '## Objective',
    '',
    'Complete the work that was interrupted by the build failure.',
    '',
    '## Plans to Execute',
    '',
    idList,
    '',
    '## Notes',
    '',
    `Original PRD: ${summary.prdId}`,
    `Deterministic evidence: ${deterministicRationale}`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Deterministic recommendation
// ---------------------------------------------------------------------------

/**
 * Compute a conservative deterministic recovery recommendation from
 * BuildFailureSummary facts. Never calls any AI agent.
 *
 * Policy:
 * - `retry`: all failed plans have terminalSubtype error_transient_transport,
 *   zero tool use counts, and no completed or merged plans exist.
 * - `split`: same transient conditions but at least one plan completed/merged
 *   before the failure (rerunning the full PRD would redo completed work).
 * - `manual`: everything else — mixed subtypes, partial/corrupt context,
 *   missing failingPlans, or non-zero tool use on any failed plan.
 */
export function determineRecoveryRecommendation(
  summary: BuildFailureSummary,
): RecoveryRecommendation {
  // Partial summary → manual (insufficient context to classify safely)
  if (summary.partial === true) {
    return {
      verdict: 'manual',
      rationale:
        'Partial summary: monitor DB context was unavailable or corrupt. ' +
        'Insufficient evidence for automated classification — human review required.',
    };
  }

  const failingPlans = summary.failingPlans;

  // No failingPlans → cannot determine terminal subtypes → manual
  if (!failingPlans || failingPlans.length === 0) {
    return {
      verdict: 'manual',
      rationale:
        'No failingPlans data in summary: cannot determine terminal subtypes ' +
        'for automated classification. Human review required.',
    };
  }

  // All failing plans must be transient-transport
  const nonTransientPlans = failingPlans.filter(p => !isTransientSubtype(p.terminalSubtype));
  if (nonTransientPlans.length > 0) {
    const desc = nonTransientPlans
      .map(p => `${p.planId} (${p.terminalSubtype ?? 'unknown'})`)
      .join(', ');
    return {
      verdict: 'manual',
      rationale:
        `Mixed or non-transient failure subtypes detected. Non-transient plans: ${desc}. ` +
        'Automated retry is not safe when failure causes are mixed.',
    };
  }

  // All transient — but any meaningful tool use means partial state may exist
  const plansWithToolUse = failingPlans.filter(
    p => typeof p.toolUseCount === 'number' && p.toolUseCount > 0,
  );
  if (plansWithToolUse.length > 0) {
    const desc = plansWithToolUse
      .map(p => `${p.planId} (toolUseCount: ${p.toolUseCount})`)
      .join(', ');
    return {
      verdict: 'manual',
      rationale:
        `Transient failure classification applies, but the following agents performed ` +
        `tool calls before failing: ${desc}. Automated retry may cause duplicate work ` +
        `or leave the repository in a partial state. Human review required.`,
    };
  }

  // All transient with zero tool use — check for partial completion
  const planIds = failingPlans.map(p => p.planId).join(', ');
  const hasCompletion = hasCompletedOrMergedPlans(summary);

  if (hasCompletion) {
    const completedPlanIds = summary.plans
      .filter(p => p.status === 'completed' || p.status === 'merged')
      .map(p => p.planId);
    const evidenceParts: string[] = [];
    if (completedPlanIds.length > 0) {
      evidenceParts.push(`Plans [${completedPlanIds.join(', ')}] completed or merged before the failure.`);
    }
    if (summary.landedCommits && summary.landedCommits.length > 0) {
      evidenceParts.push(`${summary.landedCommits.length} landed commit(s) recorded in the feature branch.`);
    }
    if (typeof summary.diffStat === 'string' && summary.diffStat.trim().length > 0) {
      evidenceParts.push(`Non-empty diff stat: ${summary.diffStat.trim()}`);
    }
    return {
      verdict: 'split',
      rationale:
        `All failed plans (${planIds}) have terminalSubtype error_transient_transport with ` +
        `zero tool use, but preserved work exists. ${evidenceParts.join(' ')} ` +
        `A successor PRD covering only the failed/remaining plans is safer than ` +
        `retrying the full original PRD and redoing completed work.`,
    };
  }

  return {
    verdict: 'retry',
    rationale:
      `All failed plans (${planIds}) have terminalSubtype error_transient_transport with ` +
      `zero tool use and no completed or merged work exists on the feature branch. ` +
      `The failure is classified as a transient API/transport error safe to retry.`,
  };
}

// ---------------------------------------------------------------------------
// Analyst verdict invariant validation
// ---------------------------------------------------------------------------

/**
 * Validate an analyst verdict against summary invariants before accepting it
 * as the final verdict.
 *
 * Invariants checked:
 * 1. Every failed plan ID from failingPlans must appear in the rationale.
 * 2. For split verdicts: suggestedSuccessorPrd must be present and must mention
 *    every failed plan ID.
 *
 * Returns `{ valid: true }` when all invariants pass, or
 * `{ valid: false, invalidationReason }` describing the first violation.
 */
export function validateAnalystVerdict(
  verdict: RecoveryVerdict,
  summary: BuildFailureSummary,
): ValidateAnalystVerdictResult {
  // Build coverage set: prefer failingPlans array, fall back to legacy failingPlan when meaningful
  let failingPlanIds: string[];
  if (summary.failingPlans && summary.failingPlans.length > 0) {
    failingPlanIds = summary.failingPlans.map(p => p.planId);
  } else if (summary.failingPlan?.planId && summary.failingPlan.planId !== 'unknown') {
    failingPlanIds = [summary.failingPlan.planId];
  } else {
    failingPlanIds = [];
  }

  // Invariant 1: all failed plan IDs must appear in the rationale
  if (failingPlanIds.length > 0) {
    const missingFromRationale = failingPlanIds.filter(id => !verdict.rationale.includes(id));
    if (missingFromRationale.length > 0) {
      return {
        valid: false,
        invalidationReason:
          `Analyst rationale does not mention failed plan IDs: ${missingFromRationale.join(', ')}. ` +
          'Every failed plan must be explicitly addressed in the rationale.',
      };
    }
  }

  // Invariant 2: split verdicts must have a complete successor PRD covering all failed AND remaining plans
  if (verdict.verdict === 'split') {
    if (!verdict.suggestedSuccessorPrd) {
      return {
        valid: false,
        invalidationReason:
          'Split verdict is missing suggestedSuccessorPrd. ' +
          'A split verdict must include a complete successor PRD covering all failed and remaining plans.',
      };
    }

    // Build the full required coverage set: failed plans + remaining non-completed/non-merged plans
    const remainingIds = summary.plans
      .filter(p => p.status !== 'completed' && p.status !== 'merged')
      .map(p => p.planId)
      .filter(id => !failingPlanIds.includes(id));
    const allRequiredIds = [...new Set([...failingPlanIds, ...remainingIds])];

    if (allRequiredIds.length > 0) {
      const missingFromSuccessor = allRequiredIds.filter(
        id => !verdict.suggestedSuccessorPrd!.includes(id),
      );
      if (missingFromSuccessor.length > 0) {
        return {
          valid: false,
          invalidationReason:
            `Successor PRD does not mention plan IDs: ${missingFromSuccessor.join(', ')}. ` +
            'The successor PRD must cover all failed and remaining plans.',
        };
      }
    }
  }

  return { valid: true };
}

// ---------------------------------------------------------------------------
// Final verdict selection
// ---------------------------------------------------------------------------

/**
 * Select the final recovery verdict by combining the deterministic recommendation
 * with analyst output and recording source metadata.
 *
 * Selection priority:
 * 1. Analyst verdict passes invariant validation → return analyst verdict with
 *    `recommendationSource: 'analyst'`.
 * 2. Analyst verdict fails invariant validation → fall back to deterministic
 *    recommendation (when retry/split) or manual-fallback, recording
 *    `verdictInvalidationReason`.
 * 3. No analyst verdict (null — timed out, threw, parse error) → use deterministic
 *    recommendation when it's retry/split, or manual-fallback otherwise.
 */
export function selectFinalVerdict(options: SelectFinalVerdictOptions): RecoveryVerdict {
  const { deterministicRecommendation, analystVerdict, analystError, parseError, summary } = options;
  const errorContext = analystError ?? parseError;

  // Case 1: Analyst produced a verdict — validate it
  if (analystVerdict !== null) {
    const validation = validateAnalystVerdict(analystVerdict, summary);

    if (validation.valid) {
      // Analyst passed invariants — use analyst verdict with source metadata
      return {
        ...analystVerdict,
        recommendationSource: 'analyst',
        recommendationRationale: deterministicRecommendation.rationale,
      };
    }

    // Analyst verdict failed invariant validation
    const invalidationReason = validation.invalidationReason!;

    if (deterministicRecommendation.verdict !== 'manual') {
      // Deterministic says retry/split — use that, annotated with invalidation info.
      // For split: ensure suggestedSuccessorPrd is populated so the sidecar is applyable.
      const deterministicSplit = deterministicRecommendation.verdict === 'split'
        ? { suggestedSuccessorPrd: synthesizeSplitSuccessorPrd(summary, deterministicRecommendation.rationale) }
        : {};
      return {
        verdict: deterministicRecommendation.verdict,
        confidence: 'medium',
        rationale: deterministicRecommendation.rationale,
        completedWork: analystVerdict.completedWork,
        remainingWork: analystVerdict.remainingWork,
        risks: analystVerdict.risks,
        ...(analystVerdict.partial !== undefined ? { partial: analystVerdict.partial } : {}),
        ...deterministicSplit,
        recommendationSource: 'deterministic',
        recommendationRationale: deterministicRecommendation.rationale,
        verdictInvalidationReason: invalidationReason,
      };
    }

    // Deterministic is also manual → manual-fallback
    return {
      verdict: 'manual',
      confidence: 'low',
      rationale:
        `Analyst verdict was rejected: ${invalidationReason} ` +
        `Deterministic policy also recommends manual review: ${deterministicRecommendation.rationale}`,
      completedWork: analystVerdict.completedWork,
      remainingWork: analystVerdict.remainingWork,
      risks: analystVerdict.risks,
      partial: summary.partial === true || analystVerdict.partial === true,
      recommendationSource: 'manual-fallback',
      recommendationRationale: deterministicRecommendation.rationale,
      verdictInvalidationReason: invalidationReason,
    };
  }

  // Case 2: No analyst verdict — use deterministic recommendation.
  // For split: ensure suggestedSuccessorPrd is populated so the sidecar is applyable.
  if (deterministicRecommendation.verdict !== 'manual') {
    const deterministicSplit = deterministicRecommendation.verdict === 'split'
      ? { suggestedSuccessorPrd: synthesizeSplitSuccessorPrd(summary, deterministicRecommendation.rationale) }
      : {};
    return {
      verdict: deterministicRecommendation.verdict,
      confidence: 'medium',
      rationale: deterministicRecommendation.rationale,
      completedWork: [],
      remainingWork: [],
      risks: [],
      partial: summary.partial === true,
      ...deterministicSplit,
      recommendationSource: 'deterministic',
      recommendationRationale: deterministicRecommendation.rationale,
      ...(errorContext !== undefined ? { recoveryError: errorContext } : {}),
    };
  }

  // Deterministic also says manual → manual-fallback
  return {
    verdict: 'manual',
    confidence: 'low',
    rationale:
      `Recovery analyst failed or output could not be parsed. ${errorContext ?? 'Unknown error.'}`,
    completedWork: [],
    remainingWork: [],
    risks: [],
    partial: summary.partial === true || analystError !== undefined,
    recommendationSource: 'manual-fallback',
    recommendationRationale: deterministicRecommendation.rationale,
    ...(errorContext !== undefined ? { recoveryError: errorContext } : {}),
  };
}
