export { EforgePlanStoreError, type EforgePlanStoreErrorCode } from './errors.js';
export { assertFts5Available } from './fts.js';
export { getEforgePlanSchemaVersion, openEforgePlanStore, resolveEforgePlanStorePath } from './db.js';
export type * from './types.js';
export { rowToBacklogItem, upsertBacklogItem, getBacklogItem, listBacklogItems, replaceBacklogItemTags, replaceBacklogItemSections, replaceItemDependencies, listItemDependencies } from './repositories/items.js';
export { rowToEpic, upsertEpic, getEpic, listEpics, replaceEpicTags, replaceEpicSections } from './repositories/epics.js';
export { rowToRecommendationRun, rowToRecommendationLane, upsertRecommendationRun, upsertRecommendationLane, replaceRecommendationLaneItems, clearCurrentRecommendationRuns, getCurrentRecommendationRun, listRecommendationRuns, deleteRecommendationLanesForRun } from './repositories/recommendations.js';
export { rowToPlanningTask, listPlanningTasks, upsertPlanningTask, replacePlanningTaskRefs } from './repositories/planning-tasks.js';
export { rowToSessionPlan, upsertSessionPlan, getSessionPlan, listSessionPlans, linkSessionPlanItems, linkSessionPlanEpics, replaceAllSessionPlanItems, replaceAllSessionPlanEpics } from './repositories/session-plans.js';
export { rowToLifecycleEvent, rowToLifecycleEvidence, recordLifecycleEvent, recordLifecycleEvidence } from './repositories/lifecycle.js';
export { rowToQueuePrd, rowToBuildRun, rowToBuildSession, rowToLandingLink, upsertQueuePrd, upsertBuildRun, upsertBuildSession, upsertLandingLink, recordQueueBuildCorrelation } from './repositories/queue-build.js';
export { rowToImportRun, rowToImportDiagnostic, recordImportRun, recordImportDiagnostic } from './repositories/import-runs.js';
export { rowToMaintenanceRun, recordMaintenanceRun, listRecentMaintenanceRuns, recordFailedMaintenanceRun } from './repositories/maintenance.js';
export * from './repositories/maintenance-pruning.js';
export { rowToSearchDocument, replaceSearchDocument, replaceSearchDocuments, deleteSearchDocument, deleteSearchDocumentsByType, deleteStaleSearchDocumentsByType, listSearchIndexDirtyRecords, clearSearchIndexDirtyRecords, rebuildSearchDocumentsFts, optimizeSearchDocumentsFts, markSearchIndexDirty, markSearchIndexDirtyBatch, clearSearchIndexDirty, getSearchIndexState } from './repositories/search-documents.js';
export * from './repositories/search-document-projections.js';
export { querySearchDocuments, countSearchDocuments, countSearchDocumentsByType, getSearchDirtyStatus, rowToSearchHitRow, hitRefs } from './repositories/search-queries.js';
export * from './repositories/projections/items.js';
export * from './repositories/projections/lifecycle.js';
export * from './repositories/projections/recommendations.js';
export * from './repositories/projections/session-plans.js';
