import { API_ROUTES } from '@eforge-build/client';

// --- eforge:region plan-01-playbook-workflow-adapter ---
async function getPlaybookAdapter() {
  const input = await import('@eforge-build/input');
  return {
    adapter: input.createPlaybookWorkflowAdapter(),
    isValidationError: input.isPlaybookWorkflowValidationError,
    isSeedCollisionError: input.isPlaybookWorkflowSessionPlanExistsError,
    isModeMismatchError: input.isPlaybookWorkflowModeMismatchError,
    analyzeAcceptanceCriteriaInBody: input.analyzeAcceptanceCriteriaInBody,
    formatAcDiagnostics: input.formatAcDiagnostics,
  };
}
// --- eforge:endregion plan-01-playbook-workflow-adapter ---

export async function listPlaybooksWire(cwd: string) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); const result = await adapter.scoped.list({ configDir: configDir ?? cwd, cwd }); for (const w of result.warnings) process.stderr.write(`${w}\n`); return result; }
export async function showPlaybook(cwd: string, name: string) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); if (!configDir) throw Object.assign(new Error('No eforge config directory found'), { statusCode: 404 }); return adapter.scoped.load({ configDir, cwd, name }); }
export async function savePlaybook(cwd: string, body: any) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter, isValidationError } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); try { const result = await adapter.scoped.save({ configDir: configDir ?? cwd, cwd, scope: body.scope, frontmatter: body.playbook.frontmatter, body: body.playbook.body }); return { path: result.path }; } catch (err) { if (isValidationError(err)) { const mapped: any = Object.assign(new Error(err.message), { statusCode: 400 }); if (err.errors) mapped.body = { error: err.message, errors: err.errors }; throw mapped; } throw err; } }
export async function runPlaybook(cwd: string, options: { queueDir?: string }, notify: () => void, body: any) { const { getConfigDir, getConventionalConfigDir, loadConfig, loadProfile } = await import('@eforge-build/engine/config'); const input = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); if (!configDir) throw Object.assign(new Error('No eforge config directory found'), { statusCode: 404 }); const { playbook } = await input.adapter.scoped.load({ configDir, cwd, name: body.name }); if (playbook.mode === 'planning') return { kind: 'requires-agent', mode: 'planning', name: body.name, message: `Playbook "${body.name}" is planning-mode. Use /eforge:playbook run ${body.name} to start an interactive planning session.` }; if (body.landingAutoMerge === true) { const { config } = await loadConfig(cwd); const effective = body.landingAction ?? (config as any).landing?.action ?? 'merge'; if (effective !== 'pr') throw Object.assign(new Error(`Invalid field: landingAutoMerge can only be true when the effective landing action is 'pr' (got '${effective}')`), { statusCode: 400 }); if ((config as any).landing?.pr?.autoMerge === 'never') throw Object.assign(new Error("landingAutoMerge: true is not allowed when landing.pr.autoMerge is 'never' in project config"), { statusCode: 400 }); } const plan = input.adapter.scoped.compileAutonomous(playbook); const ac = input.analyzeAcceptanceCriteriaInBody(plan.source); if (ac && !ac.valid) throw Object.assign(new Error(`Playbook acceptance criteria quality gate failed:\n${input.formatAcDiagnostics(ac.diagnostics)}`), { statusCode: 400 }); const { deriveAcceptanceCriteriaInventoryFromPrdBody } = await import('@eforge-build/engine/validation/acceptance-criteria-inventory'); let acceptanceCriteriaInventory; try { acceptanceCriteriaInventory = deriveAcceptanceCriteriaInventoryFromPrdBody(plan.source); } catch (e) { throw Object.assign(new Error(e instanceof Error ? e.message : String(e)), { statusCode: 400 }); } if (playbook.profile) { const cfgDir = await getConfigDir(cwd) ?? getConventionalConfigDir(cwd); if (!await loadProfile(cfgDir, playbook.profile, cwd)) throw Object.assign(new Error(`Playbook profile '${playbook.profile}' not found`), { statusCode: 400 }); }
  const { enqueuePrd, inferTitle, classifyAfterQueueId } = await import('@eforge-build/engine/prd-queue'); const queueDir = options.queueDir ?? '.eforge/queue'; let depends_on: string[] | undefined; let intoWaiting = false; if (body.afterQueueId) { try { const p = await classifyAfterQueueId(body.afterQueueId, queueDir, cwd); depends_on = p.dependsOn; intoWaiting = p.intoWaiting; } catch (e) { throw Object.assign(new Error(e instanceof Error ? e.message : `Invalid afterQueueId: ${body.afterQueueId}`), { statusCode: 404 }); } } const result = await enqueuePrd({ body: plan.source, title: inferTitle(plan.source, plan.name), queueDir, cwd, depends_on, intoWaiting, postMerge: plan.postMerge, profile: plan.profile, acceptanceCriteriaInventory, ...(body.landingAction !== undefined && { landingAction: body.landingAction }), ...(body.landingAutoMerge !== undefined && { landingAutoMerge: body.landingAutoMerge }) }); notify(); return { kind: 'enqueued', id: result.id }; }
export async function movePlaybookWire(cwd: string, name: string, promote: boolean) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); if (!configDir) throw Object.assign(new Error('No eforge config directory found'), { statusCode: 404 }); const result = promote ? await adapter.scoped.promote({ configDir, cwd, name }) : await adapter.scoped.demote({ configDir, cwd, name }); return { path: result.path }; }
export async function validatePlaybookRaw(raw: string) { const { adapter } = await getPlaybookAdapter(); const result = adapter.scoped.validateRaw(raw); return result.ok ? { ok: true } : { ok: false, errors: result.errors }; }
export async function copyPlaybookWire(cwd: string, body: any) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); if (!configDir) throw Object.assign(new Error('No eforge config directory found'), { statusCode: 404 }); const r = await adapter.scoped.copy({ configDir, cwd, name: body.name, targetScope: body.targetScope }); return { sourcePath: r.sourcePath, targetPath: r.targetPath, targetScope: r.targetScope }; }
export async function createFromPlaybook(cwd: string, body: any) { const { getConfigDir } = await import('@eforge-build/engine/config'); const { adapter, isSeedCollisionError, isModeMismatchError } = await getPlaybookAdapter(); const configDir = await getConfigDir(cwd); if (!configDir) throw Object.assign(new Error('No eforge config directory found'), { statusCode: 404 }); try { const result = await adapter.scoped.seedPlanningSessionPlan({ configDir, cwd, name: body.playbook_name, session: typeof body.session === 'string' ? body.session : undefined, topic: typeof body.topic === 'string' ? body.topic : undefined }); return { session: result.session, path: result.path }; } catch (err) { if (isModeMismatchError(err)) throw Object.assign(new Error(`Playbook "${body.playbook_name}" is autonomous — use POST ${API_ROUTES.playbookRun} to enqueue it`), { statusCode: 400 }); if (isSeedCollisionError(err)) throw Object.assign(new Error(err.message), { statusCode: 409 }); throw err; } }
