import { API_ROUTES } from '@eforge-build/client';
import type { MonitorContext } from '../context.js';
import { defineRoute, type ApiRouteKey, type RequestContext, type RouteDefinition } from '../http/router.js';
import { isRequestBodyTooLargeError, parseJsonBody } from '../http/request.js';
import { sendJson, sendJsonError } from '../http/response.js';
import { localMutation, localOnly, rejectCrossSiteBrowser } from '../http/security.js';
import { isValidPlaybookName } from './content-validation.js';
import * as svc from './playbook-service.js';

export function createPlaybookRoutes(context: MonitorContext): RouteDefinition[] { const readSecurity = [localOnly('Playbook reads'), rejectCrossSiteBrowser('Playbook reads')]; return [
  defineRoute({ routeKey: 'playbookList', method: 'GET', pattern: API_ROUTES.playbookList, security: readSecurity, handler: (ctx) => withCwd(ctx, context, () => svc.listPlaybooksWire(context.cwd!)) }),
  defineRoute({ routeKey: 'playbookShow', method: 'GET', pattern: API_ROUTES.playbookShow, security: readSecurity, handler: (ctx) => { const name = ctx.query.get('name'); if (!name) return sendJsonError(ctx.res, 400, 'Missing required query param: name'); if (!isValidPlaybookName(name)) return sendJsonError(ctx.res, 400, 'Invalid playbook name (must be kebab-case)'); return withCwd(ctx, context, () => svc.showPlaybook(context.cwd!, name)); } }),
  post('playbookSave', context, validateSave, (b) => svc.savePlaybook(context.cwd!, b)),
  post('playbookRun', context, validateRun, (b) => svc.runPlaybook(context.cwd!, { queueDir: context.options.queueDir }, () => context.notifyQueueMutation('playbook-enqueue'), b)),
  post('playbookPromote', context, validateName, (b) => svc.movePlaybookWire(context.cwd!, b.name, true)),
  post('playbookDemote', context, validateName, (b) => svc.movePlaybookWire(context.cwd!, b.name, false)),
  post('playbookValidate', context, (b) => (!b.raw || typeof b.raw !== 'string' ? 'Missing required field: raw (string)' : undefined), (b) => svc.validatePlaybookRaw(b.raw), false),
  post('playbookCopy', context, validateCopy, (b) => svc.copyPlaybookWire(context.cwd!, b)),
  post('sessionPlanCreateFromPlaybook', context, validateCreateFrom, (b) => svc.createFromPlaybook(context.cwd!, b)),
]; }
function withCwd(ctx: RequestContext, context: MonitorContext, run: () => Promise<unknown>) { if (!context.cwd) return sendJsonError(ctx.res, 503, 'Working directory not configured'); return run().then((r) => sendJson(ctx.res, r)).catch((e) => mapErr(ctx, e)); }
function post(routeKey: ApiRouteKey, context: MonitorContext, validate: (b: any) => string | undefined, run: (b: any) => Promise<unknown>, mapNotFound = true): RouteDefinition { const security = routeKey === 'playbookValidate' ? undefined : [localMutation('Playbook mutations')]; return defineRoute({ routeKey, method: 'POST', pattern: API_ROUTES[routeKey], security, handler: async (ctx) => { if (!context.cwd && routeKey !== 'playbookValidate') return sendJsonError(ctx.res, 503, 'Working directory not configured'); let body: any; try { body = await parseJsonBody(ctx.req); } catch (err) { return sendJsonError(ctx.res, isRequestBodyTooLargeError(err) ? 413 : 400, isRequestBodyTooLargeError(err) ? 'Request body too large' : 'Invalid JSON body'); } if (!body || typeof body !== 'object' || Array.isArray(body)) return sendJsonError(ctx.res, 400, 'Invalid JSON body'); const error = validate(body); if (error) return sendJsonError(ctx.res, 400, error); try { sendJson(ctx.res, await run(body)); } catch (err) { if ((err as any).body) return sendJson(ctx.res, (err as any).body, (err as any).statusCode ?? 400); mapErr(ctx, err, mapNotFound); } } }); }
function validateName(b: any) { if (!b.name || typeof b.name !== 'string') return 'Missing required field: name (string)'; if (!isValidPlaybookName(b.name)) return 'Invalid playbook name (must be kebab-case)'; }
function validateSave(b: any) { if (!['user', 'project-team', 'project-local'].includes(b.scope)) return 'Missing or invalid field: scope (must be "user", "project-team", or "project-local")'; if (!b.playbook || typeof b.playbook !== 'object') return 'Missing required field: playbook'; }
function validateRun(b: any) { return validateName(b) ?? (b.afterQueueId !== undefined && typeof b.afterQueueId !== 'string' ? 'Invalid field: afterQueueId must be a string' : undefined) ?? (b.afterQueueId === '' ? 'Invalid field: afterQueueId must not be empty' : undefined) ?? (b.onSuccess !== undefined ? 'Field "onSuccess" is no longer supported. Use "landingAction: pr|merge|leave" instead.' : undefined) ?? (b.landingAction !== undefined && !['pr', 'merge', 'leave'].includes(b.landingAction) ? 'Invalid landingAction value: must be one of pr, merge, leave' : undefined) ?? (b.landingAutoMerge !== undefined && typeof b.landingAutoMerge !== 'boolean' ? 'Invalid field: landingAutoMerge must be a boolean' : undefined); }
function validateCopy(b: any) { return validateName(b) ?? (!['project-local', 'project-team', 'user'].includes(b.targetScope) ? 'Missing or invalid field: targetScope (must be "project-local", "project-team", or "user")' : undefined); }
function validateCreateFrom(b: any) { if (!b.playbook_name || typeof b.playbook_name !== 'string') return 'Missing required field: playbook_name (string)'; if (!isValidPlaybookName(b.playbook_name)) return 'Invalid playbook name (must be kebab-case)'; }
function mapErr(ctx: RequestContext, err: unknown, mapNotFound = true) { const msg = err instanceof Error ? err.message : 'Failed to run playbook'; const status = (err as any).statusCode ?? (mapNotFound && (/not found/i.test(msg) || /enoent/i.test(msg)) ? 404 : /escape|traversal|invalid session/i.test(msg) ? 400 : 500); sendJsonError(ctx.res, status, msg); }
