import { API_ROUTES } from '@eforge-build/client';
import type { MonitorContext } from '../context.js';
import { defineRoute, type ApiRouteKey, type RequestContext, type RouteDefinition } from '../http/router.js';
import { isRequestBodyTooLargeError, parseJsonBody } from '../http/request.js';
import { sendJson, sendJsonError } from '../http/response.js';
import { localMutation, localOnly, rejectCrossSiteBrowser } from '../http/security.js';
import { includeSubmittedFromQuery, isValidSessionPlanId, VALID_PLANNING_DEPTHS, VALID_PLANNING_TYPES, VALID_PROFILES, VALID_SESSION_PLAN_STATUSES, validateEnum } from './content-validation.js';
import * as svc from './session-plan-service.js';

export function createSessionPlanRoutes(context: MonitorContext): RouteDefinition[] { const readSecurity = [localOnly('Session plan reads'), rejectCrossSiteBrowser('Session plan reads')]; return [
  defineRoute({ routeKey: 'sessionPlanList', method: 'GET', pattern: API_ROUTES.sessionPlanList, security: readSecurity, handler: (ctx) => withCwd(ctx, context, () => svc.listSessionPlansWire(context.cwd!, includeSubmittedFromQuery(ctx.query))) }),
  defineRoute({ routeKey: 'sessionPlanShow', method: 'GET', pattern: API_ROUTES.sessionPlanShow, security: readSecurity, handler: (ctx) => requireSessionQuery(ctx, context, (s) => svc.showSessionPlan(context.cwd!, s)) }),
  post('sessionPlanCreate', context, validateCreate, (b) => svc.createSessionPlanWire(context.cwd!, b), 'Failed to create session plan'),
  post('sessionPlanSetSection', context, validateSetSection, (b) => svc.setSection(context.cwd!, b), 'Failed to set session plan section'),
  post('sessionPlanSkipDimension', context, validateSkip, (b) => svc.skipDimensionWire(context.cwd!, b), 'Failed to skip session plan dimension'),
  post('sessionPlanSetStatus', context, validateStatus, (b) => svc.setStatusWire(context.cwd!, b), 'Failed to set session plan status'),
  post('sessionPlanSelectDimensions', context, validateSelect, (b) => svc.selectDimensionsWire(context.cwd!, b), 'Failed to select session plan dimensions'),
  defineRoute({ routeKey: 'sessionPlanReadiness', method: 'GET', pattern: API_ROUTES.sessionPlanReadiness, security: readSecurity, handler: (ctx) => requireSessionQuery(ctx, context, (s) => svc.readinessWire(context.cwd!, s)) }),
  post('sessionPlanMigrateLegacy', context, (b) => validateSessionBody(b), (b) => svc.migrateLegacy(context.cwd!, b.session), 'Failed to migrate session plan'),
]; }
function withCwd(ctx: RequestContext, context: MonitorContext, run: () => Promise<unknown>) { if (!context.cwd) return sendJsonError(ctx.res, 503, 'Working directory not configured'); return run().then((r) => sendJson(ctx.res, r)).catch((e) => sendJsonError(ctx.res, 500, e instanceof Error ? e.message : 'Server error')); }
function requireSessionQuery(ctx: RequestContext, context: MonitorContext, run: (s: string) => Promise<unknown>, showBadAs400 = true) { if (!context.cwd) return sendJsonError(ctx.res, 503, 'Working directory not configured'); const session = ctx.query.get('session'); if (!session) return sendJsonError(ctx.res, 400, 'Missing required query param: session'); if (!isValidSessionPlanId(session)) return sendJsonError(ctx.res, 400, 'Invalid session id (must be kebab-case)'); return run(session).then((r) => sendJson(ctx.res, r)).catch((err) => mapErr(ctx, err, showBadAs400)); }
function post(routeKey: ApiRouteKey, context: MonitorContext, validate: (b: any) => string | undefined, run: (b: any) => Promise<unknown>, fallback: string): RouteDefinition { return defineRoute({ routeKey, method: 'POST', pattern: API_ROUTES[routeKey], security: [localMutation('Session plan mutations')], handler: async (ctx) => { if (!context.cwd) return sendJsonError(ctx.res, 503, 'Working directory not configured'); let body: any; try { body = await parseJsonBody(ctx.req); } catch (err) { return sendJsonError(ctx.res, isRequestBodyTooLargeError(err) ? 413 : 400, isRequestBodyTooLargeError(err) ? 'Request body too large' : 'Invalid JSON body'); } if (!body || typeof body !== 'object' || Array.isArray(body)) return sendJsonError(ctx.res, 400, 'Invalid JSON body'); const error = validate(body); if (error) return sendJsonError(ctx.res, 400, error); try { sendJson(ctx.res, await run(body)); } catch (err) { if ((err as any).body) return sendJson(ctx.res, (err as any).body, (err as any).statusCode ?? 400); mapErr(ctx, err, true, fallback); } } }); }
function validateSessionBody(b: any) { if (!b.session || typeof b.session !== 'string') return 'Missing required field: session (string)'; if (!isValidSessionPlanId(b.session)) return 'Invalid session id (must be kebab-case)'; }
function validateCreate(b: any) { return validateSessionBody(b) ?? (!b.topic || typeof b.topic !== 'string' ? 'Missing required field: topic (string)' : undefined) ?? (b.planning_type !== undefined && !validateEnum(b.planning_type, VALID_PLANNING_TYPES) ? `Invalid planning_type (must be one of: ${VALID_PLANNING_TYPES.join(', ')})` : undefined) ?? (b.planning_depth !== undefined && !validateEnum(b.planning_depth, VALID_PLANNING_DEPTHS) ? `Invalid planning_depth (must be one of: ${VALID_PLANNING_DEPTHS.join(', ')})` : undefined) ?? (b.profile !== undefined && b.profile !== null && !validateEnum(b.profile, VALID_PROFILES) ? `Invalid profile (must be null or one of: ${VALID_PROFILES.join(', ')})` : undefined) ?? (b.agent_profile !== undefined && typeof b.agent_profile !== 'string' ? 'Invalid agent_profile (must be a string)' : undefined); }
function validateSetSection(b: any) { return validateSessionBody(b) ?? (!b.dimension || typeof b.dimension !== 'string' ? 'Missing required field: dimension (string)' : undefined) ?? (typeof b.content !== 'string' ? 'Missing required field: content (string)' : undefined); }
function validateSkip(b: any) { return validateSessionBody(b) ?? (!b.dimension || typeof b.dimension !== 'string' ? 'Missing required field: dimension (string)' : undefined) ?? (!b.reason || typeof b.reason !== 'string' ? 'Missing required field: reason (string)' : undefined); }
function validateStatus(b: any) { return validateSessionBody(b) ?? (!b.status || typeof b.status !== 'string' ? 'Missing required field: status (string)' : undefined) ?? (!validateEnum(b.status, VALID_SESSION_PLAN_STATUSES) ? 'Invalid status (must be "planning", "ready", "abandoned", or "submitted")' : undefined) ?? (b.status === 'submitted' && (!b.eforge_session || typeof b.eforge_session !== 'string') ? 'eforge_session is required when status is "submitted"' : undefined); }
function validateSelect(b: any) { return validateSessionBody(b) ?? (b.planning_type !== undefined && !validateEnum(b.planning_type, VALID_PLANNING_TYPES) ? `Invalid planning_type (must be one of: ${VALID_PLANNING_TYPES.join(', ')})` : undefined) ?? (b.planning_depth !== undefined && !validateEnum(b.planning_depth, VALID_PLANNING_DEPTHS) ? `Invalid planning_depth (must be one of: ${VALID_PLANNING_DEPTHS.join(', ')})` : undefined) ?? (b.overwrite !== undefined && typeof b.overwrite !== 'boolean' ? 'Invalid field: overwrite must be a boolean' : undefined); }
function mapErr(ctx: RequestContext, err: unknown, badAs400: boolean, fallback = 'Failed to load session plan') { const msg = err instanceof Error ? err.message : fallback; if (/not found/i.test(msg) || /enoent/i.test(msg)) sendJsonError(ctx.res, 404, msg); else sendJsonError(ctx.res, badAs400 && (/invalid|required/i.test(msg)) ? 400 : 500, msg); }
