import { Type } from '@eforge-build/extension-sdk';
import { BacklogStatusSchema, KanbanLaneSchema } from '../schema.js';

export const SearchDocumentTypeSchema = Type.Union([Type.Literal('backlog_item'), Type.Literal('epic'), Type.Literal('session_plan'), Type.Literal('recommendation')]);
export const SearchSelectedFieldSchema = Type.Union([Type.Literal('rank'), Type.Literal('snippet'), Type.Literal('refs'), Type.Literal('updatedAt')]);
export const SearchSnippetSchema = Type.Object({ text: Type.String(), field: Type.Optional(Type.Union([Type.Literal('title'), Type.Literal('tags'), Type.Literal('summary'), Type.Literal('body'), Type.Literal('itemIds'), Type.Literal('epicIds'), Type.Literal('recommendationRefs')])), highlights: Type.Array(Type.String()) }, { additionalProperties: false });
export const SearchIndexStatusSchema = Type.Object({ dirty: Type.Boolean(), dirtyCount: Type.Integer({ minimum: 0 }), dirtyTypes: Type.Array(SearchDocumentTypeSchema), dirtySince: Type.Optional(Type.String()), dirtyReason: Type.Optional(Type.String()), lastRebuiltAt: Type.Optional(Type.String()) }, { additionalProperties: false });
export const SearchPageSchema = Type.Object({ limit: Type.Integer({ minimum: 1 }), offset: Type.Integer({ minimum: 0 }), returned: Type.Integer({ minimum: 0 }), hasMore: Type.Boolean(), nextOffset: Type.Optional(Type.Integer({ minimum: 0 })) }, { additionalProperties: false });

const CompactItemSchema = Type.Object({ id: Type.String(), title: Type.String(), status: BacklogStatusSchema, priority: Type.String(), tags: Type.Array(Type.String()), lane: KanbanLaneSchema, reasons: Type.Array(Type.String()), dependsOn: Type.Optional(Type.Array(Type.String())), unresolvedDependsOn: Type.Optional(Type.Array(Type.String())), activeTraceReasons: Type.Array(Type.String()), blocked: Type.Boolean(), ready: Type.Boolean(), reviewDue: Type.Boolean(), closed: Type.Boolean(), hasBody: Type.Optional(Type.Boolean()), updatedAt: Type.Optional(Type.String()), epic: Type.Optional(Type.String()), lifecycleState: Type.String(), userStatus: Type.Optional(BacklogStatusSchema), effectiveLifecycle: Type.Optional(Type.String()), reasonCodes: Type.Optional(Type.Array(Type.String())), associatedLinks: Type.Optional(Type.Array(Type.Object({}, { additionalProperties: Type.Unknown() }))), rank: Type.Optional(Type.Number()), snippet: Type.Optional(SearchSnippetSchema), matchedFields: Type.Optional(Type.Array(Type.String())) }, { additionalProperties: false });
const CompactEpicSchema = Type.Object({ id: Type.String(), title: Type.String(), status: BacklogStatusSchema, userStatus: Type.Optional(BacklogStatusSchema), priority: Type.Optional(Type.String()), tags: Type.Array(Type.String()), itemCount: Type.Integer({ minimum: 0 }), totalItems: Type.Optional(Type.Integer({ minimum: 0 }),), openItemCount: Type.Integer({ minimum: 0 }), hasBody: Type.Boolean() }, { additionalProperties: false });
const PageInputFields = { limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 500 })), offset: Type.Optional(Type.Integer({ minimum: 0 })) };
const SearchQuerySchema = Type.String({ maxLength: 500 });
const SearchRefSchema = Type.String({ minLength: 1, maxLength: 200, pattern: '\\S' });
const SearchTagSchema = Type.String({ minLength: 1, maxLength: 100, pattern: '\\S' });

export const SearchItemsInputSchema = Type.Object({ query: Type.Optional(SearchQuerySchema), epic: Type.Optional(SearchRefSchema), status: Type.Optional(BacklogStatusSchema), lane: Type.Optional(KanbanLaneSchema), tags: Type.Optional(Type.Array(SearchTagSchema, { maxItems: 50, uniqueItems: true })), includeArchive: Type.Optional(Type.Boolean()), searchBody: Type.Optional(Type.Boolean()), includeEpics: Type.Optional(Type.Boolean()), includeDependencies: Type.Optional(Type.Boolean()), ...PageInputFields }, { additionalProperties: false });
export const SearchItemsOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), items: Type.Array(CompactItemSchema), epics: Type.Optional(Type.Array(CompactEpicSchema)), total: Type.Integer({ minimum: 0 }), limit: Type.Integer({ minimum: 1 }), offset: Type.Integer({ minimum: 0 }), snippets: Type.Optional(Type.Record(Type.String(), SearchSnippetSchema)), counts: Type.Optional(Type.Object({ total: Type.Integer({ minimum: 0 }) }, { additionalProperties: false })), pagination: SearchPageSchema, indexDirty: Type.Boolean(), indexStatus: SearchIndexStatusSchema }, { additionalProperties: false });
export const SearchPlanningRecordsInputSchema = Type.Object({ query: Type.Optional(SearchQuerySchema), types: Type.Optional(Type.Array(SearchDocumentTypeSchema, { maxItems: 4, uniqueItems: true })), itemIds: Type.Optional(Type.Array(SearchRefSchema, { maxItems: 100, uniqueItems: true })), epicIds: Type.Optional(Type.Array(SearchRefSchema, { maxItems: 100, uniqueItems: true })), sessions: Type.Optional(Type.Array(SearchRefSchema, { maxItems: 100, uniqueItems: true })), recommendationRefs: Type.Optional(Type.Array(SearchRefSchema, { maxItems: 100, uniqueItems: true })), includeHistoricalRecommendations: Type.Optional(Type.Boolean()), fields: Type.Optional(Type.Array(SearchSelectedFieldSchema, { maxItems: 4, uniqueItems: true })), ...PageInputFields }, { additionalProperties: false });
const SearchResultSchema = Type.Object({ type: SearchDocumentTypeSchema, id: Type.String(), title: Type.String(), rank: Type.Optional(Type.Number()), snippet: Type.Optional(SearchSnippetSchema), refs: Type.Optional(Type.Object({ itemIds: Type.Optional(Type.Array(Type.String())), epicIds: Type.Optional(Type.Array(Type.String())), session: Type.Optional(Type.String()), recommendationRef: Type.Optional(Type.String()), runId: Type.Optional(Type.String()) }, { additionalProperties: false })), updatedAt: Type.Optional(Type.String()) }, { additionalProperties: false });
export const SearchPlanningRecordsOutputSchema = Type.Object({ schemaVersion: Type.Literal(1), results: Type.Array(SearchResultSchema), total: Type.Integer({ minimum: 0 }), countsByType: Type.Partial(Type.Record(SearchDocumentTypeSchema, Type.Integer({ minimum: 0 }))), page: SearchPageSchema, indexDirty: Type.Boolean(), indexStatus: SearchIndexStatusSchema }, { additionalProperties: false });
