import type { EforgePlanStore, LifecycleState } from '../../types.js';
import { all, optionalString, parseJsonColumn } from '../sql.js';

export interface ProjectionLifecycleEvidenceRow { evidenceKey: string; itemId: string; itemRef: string; lifecycleState: LifecycleState; reasonCode?: string; evidenceKind?: string; status?: string; session?: string; planningTaskId?: string; queuePrdId?: string; queuePrdStatus?: string; runId?: string; buildSessionId?: string; landingId?: string; occurredAt?: string; summary?: string; isCurrent: boolean; isTerminal: boolean; links?: unknown }
export interface ProjectionSessionItemRow { session: string; itemId?: string; itemRef: string; role: string; provenance: string; sourceTaskId?: string; sourceRecommendationRef?: string; promotedAt?: string; sequence?: number; status?: string; path?: string }
export interface ProjectionPlanningTaskItemRow { taskId: string; itemId?: string; itemRef: string; role?: string; status?: string; updatedAt?: string; createdAt?: string }
export interface ProjectionQueueBuildRow { kind: 'queue-prd' | 'build-run' | 'build-session' | 'landing'; id: string; itemId?: string; session?: string; status?: string; timestamp?: string; path?: string; url?: string; runId?: string; buildSessionId?: string; queuePrdId?: string }

export function rowToProjectionLifecycleEvidence(row: Record<string, unknown>): ProjectionLifecycleEvidenceRow { return { evidenceKey: row.evidence_key as string, itemId: optionalString(row.item_id) ?? row.item_ref as string, itemRef: row.item_ref as string, lifecycleState: row.lifecycle_state as LifecycleState, reasonCode: optionalString(row.reason_code), evidenceKind: optionalString(row.evidence_kind), status: optionalString(row.status), session: optionalString(row.session), planningTaskId: optionalString(row.planning_task_id), queuePrdId: optionalString(row.queue_prd_id), queuePrdStatus: optionalString(row.queue_prd_status), runId: optionalString(row.run_id), buildSessionId: optionalString(row.build_session_id), landingId: optionalString(row.landing_id), occurredAt: optionalString(row.occurred_at), summary: optionalString(row.summary), isCurrent: Number(row.is_current) === 1, isTerminal: Number(row.is_terminal) === 1, links: parseJsonColumn('lifecycle_evidence','links_json', row.links_json) }; }
const LIFECYCLE_EVIDENCE_PROJECTION_SQL = 'SELECT le.*, qp.status AS queue_prd_status FROM lifecycle_evidence le LEFT JOIN queue_prds qp ON qp.prd_id = le.queue_prd_id';
export function listCurrentLifecycleEvidence(store: EforgePlanStore): ProjectionLifecycleEvidenceRow[] { return all<Record<string, unknown>>(store, `${LIFECYCLE_EVIDENCE_PROJECTION_SQL} WHERE le.is_current = 1 ORDER BY le.occurred_at DESC, le.evidence_key`).map(rowToProjectionLifecycleEvidence); }
export function listLifecycleEvidenceForItems(store: EforgePlanStore, itemIds: readonly string[]): ProjectionLifecycleEvidenceRow[] { if (itemIds.length === 0) return []; const q = itemIds.map(() => '?').join(','); return all<Record<string, unknown>>(store, `${LIFECYCLE_EVIDENCE_PROJECTION_SQL} WHERE (le.item_id IN (${q}) OR le.item_ref IN (${q})) AND le.is_current = 1 ORDER BY le.occurred_at DESC, le.evidence_key`, ...itemIds, ...itemIds).map(rowToProjectionLifecycleEvidence); }
export function listProjectionSessionItems(store: EforgePlanStore): ProjectionSessionItemRow[] { return all<Record<string, unknown>>(store, `SELECT spi.*, sp.status, sp.path FROM session_plan_items spi JOIN session_plans sp ON sp.session = spi.session ORDER BY spi.session, spi.sequence`).map((r) => ({ session: r.session as string, itemId: optionalString(r.item_id), itemRef: r.item_ref as string, role: r.role as string, provenance: r.provenance as string, sourceTaskId: optionalString(r.source_task_id), sourceRecommendationRef: optionalString(r.source_recommendation_ref), promotedAt: optionalString(r.promoted_at), sequence: typeof r.sequence === 'number' ? r.sequence : undefined, status: optionalString(r.status), path: optionalString(r.path) })); }
export function listProjectionPlanningTaskItems(store: EforgePlanStore): ProjectionPlanningTaskItemRow[] { return all<Record<string, unknown>>(store, `SELECT pti.*, pt.status_snapshot, pt.updated_at, pt.created_at FROM planning_task_items pti JOIN planning_tasks pt ON pt.task_id = pti.task_id ORDER BY pt.updated_at DESC, pti.sequence`).map((r) => ({ taskId: r.task_id as string, itemId: optionalString(r.item_id), itemRef: r.item_ref as string, role: optionalString(r.role), status: optionalString(r.status_snapshot), updatedAt: optionalString(r.updated_at), createdAt: optionalString(r.created_at) })); }
export function listProjectionQueueBuildLinks(store: EforgePlanStore): ProjectionQueueBuildRow[] {
  const queues = all<Record<string, unknown>>(store, 'SELECT * FROM queue_prds').map((r) => ({ kind: 'queue-prd' as const, id: r.prd_id as string, session: optionalString(r.session), status: optionalString(r.status), timestamp: optionalString(r.updated_at) ?? optionalString(r.submitted_at) ?? optionalString(r.created_at), path: optionalString(r.source_path), queuePrdId: r.prd_id as string }));
  const runs = all<Record<string, unknown>>(store, 'SELECT * FROM build_runs').map((r) => ({ kind: 'build-run' as const, id: r.run_id as string, session: optionalString(r.session), status: optionalString(r.status), timestamp: optionalString(r.finished_at) ?? optionalString(r.started_at), runId: r.run_id as string, buildSessionId: optionalString(r.build_session_id), queuePrdId: optionalString(r.queue_prd_id) }));
  const sessions = all<Record<string, unknown>>(store, 'SELECT * FROM build_sessions').map((r) => ({ kind: 'build-session' as const, id: r.build_session_id as string, session: optionalString(r.session), status: optionalString(r.status), timestamp: optionalString(r.finished_at) ?? optionalString(r.started_at), buildSessionId: r.build_session_id as string }));
  const landings = all<Record<string, unknown>>(store, 'SELECT * FROM landing_links').map((r) => ({ kind: 'landing' as const, id: r.landing_id as string, itemId: optionalString(r.item_id), session: optionalString(r.session), status: optionalString(r.status), timestamp: optionalString(r.completed_at) ?? optionalString(r.created_at), url: optionalString(r.pr_url), runId: optionalString(r.run_id), buildSessionId: optionalString(r.build_session_id), queuePrdId: optionalString(r.queue_prd_id) }));
  return [...queues, ...runs, ...sessions, ...landings];
}
