import type { EforgePlanStore, LaneKind, RecommendationItemRole } from '../../types.js';
import { all, one, optionalString, parseJsonColumn } from '../sql.js';

export interface ProjectionRecommendationRunRow { runId: string; createdAt?: string; appliedAt?: string; isCurrent: boolean; rawModel?: unknown; summary?: unknown; freshness?: unknown; sourceFingerprint?: string; lastRefreshedBy?: string }
export interface ProjectionRecommendationLaneRow { laneId: string; runId: string; laneKind: LaneKind; laneRef?: string; title?: string; sequence: number; profile?: string; rationale?: string }
export interface ProjectionRecommendationLaneItemRow { laneId: string; itemRef: string; itemId?: string; role: RecommendationItemRole; sequence: number; rationale?: string; confidence?: number }
export function getCurrentProjectionRecommendationRun(store: EforgePlanStore): ProjectionRecommendationRunRow | undefined { const r = one<Record<string, unknown>>(store, 'SELECT * FROM recommendation_runs WHERE is_current = 1 ORDER BY created_at DESC LIMIT 1'); return r ? { runId: r.run_id as string, createdAt: optionalString(r.created_at), appliedAt: optionalString(r.applied_at), isCurrent: Number(r.is_current) === 1, rawModel: parseJsonColumn('recommendation_runs','raw_model_json', r.raw_model_json), summary: parseJsonColumn('recommendation_runs','summary_json', r.summary_json), freshness: parseJsonColumn('recommendation_runs','freshness_json', r.freshness_json), sourceFingerprint: optionalString(r.source_fingerprint), lastRefreshedBy: optionalString(r.last_refreshed_by) } : undefined; }
export function listProjectionRecommendationLanes(store: EforgePlanStore, runId: string): ProjectionRecommendationLaneRow[] { return all<Record<string, unknown>>(store, 'SELECT * FROM recommendation_lanes WHERE run_id = ? ORDER BY sequence, lane_id', runId).map((r) => ({ laneId: r.lane_id as string, runId: r.run_id as string, laneKind: r.lane_kind as LaneKind, laneRef: optionalString(r.lane_ref), title: optionalString(r.title), sequence: Number(r.sequence ?? 0), profile: optionalString(r.profile), rationale: optionalString(r.rationale) })); }
export function listProjectionRecommendationLaneItems(store: EforgePlanStore, runId: string): ProjectionRecommendationLaneItemRow[] { return all<Record<string, unknown>>(store, `SELECT rli.* FROM recommendation_lane_items rli JOIN recommendation_lanes rl ON rl.lane_id = rli.lane_id WHERE rl.run_id = ? ORDER BY rl.sequence, rli.sequence, rli.item_ref`, runId).map((r) => ({ laneId: r.lane_id as string, itemRef: r.item_ref as string, itemId: optionalString(r.item_id), role: r.role as RecommendationItemRole, sequence: Number(r.sequence ?? 0), rationale: optionalString(r.rationale), confidence: typeof r.confidence === 'number' ? r.confidence : undefined })); }
