import { TERMINAL_SESSION_STATUSES } from '../../../planning-state-policy.js';
import type { EforgePlanStore } from '../../types.js';
import { all, one, optionalString, parseJsonColumn } from '../sql.js';

export interface ProjectionSessionPlanRow { session: string; path?: string; topic?: string; status?: string; planningType?: string; planningDepth?: string; profile?: string; agentProfile?: string; eforgeSessionId?: string; submittedAt?: string; createdAt?: string; updatedAt?: string; summaryText?: string; artifactBodyHash?: string; readinessSummary?: unknown; frontmatter: Record<string, unknown> }
export interface ProjectionSessionPlanItemRow { session: string; itemRef: string; itemId?: string; role: string; provenance: string; sourceTaskId?: string; sourceRecommendationRef?: string; promotedAt?: string; sequence?: number }
function rowToProjectionSessionPlan(r: Record<string, unknown>): ProjectionSessionPlanRow { return { session: r.session as string, path: optionalString(r.path), topic: optionalString(r.topic), status: optionalString(r.status), planningType: optionalString(r.planning_type), planningDepth: optionalString(r.planning_depth), profile: optionalString(r.profile), agentProfile: optionalString(r.agent_profile), eforgeSessionId: optionalString(r.eforge_session_id), submittedAt: optionalString(r.submitted_at), createdAt: optionalString(r.created_at), updatedAt: optionalString(r.updated_at), summaryText: optionalString(r.summary_text), artifactBodyHash: optionalString(r.artifact_body_hash), readinessSummary: parseJsonColumn('session_plans','readiness_summary_json', r.readiness_summary_json), frontmatter: parseJsonColumn('session_plans','frontmatter_json', r.frontmatter_json, {}) as Record<string, unknown> }; }
export function listProjectionSessionPlans(store: EforgePlanStore, includeSubmitted = false): ProjectionSessionPlanRow[] { const placeholders = TERMINAL_SESSION_STATUSES.map(() => '?').join(','); const hidden = `COALESCE(lower(trim(status)),'draft') NOT IN (${placeholders}) AND COALESCE(import_origin,'') <> 'trace-sidecar'`; return all<Record<string, unknown>>(store, includeSubmitted ? `SELECT * FROM session_plans WHERE ${hidden} ORDER BY updated_at DESC, session` : `SELECT * FROM session_plans WHERE ${hidden} AND COALESCE(lower(trim(status)),'draft') <> 'submitted' ORDER BY updated_at DESC, session`, ...TERMINAL_SESSION_STATUSES).map(rowToProjectionSessionPlan); }
export function listAllProjectionSessionPlans(store: EforgePlanStore): ProjectionSessionPlanRow[] { return all<Record<string, unknown>>(store, "SELECT * FROM session_plans WHERE COALESCE(import_origin,'') <> 'trace-sidecar' ORDER BY updated_at DESC, session").map(rowToProjectionSessionPlan); }
export function getProjectionSessionPlan(store: EforgePlanStore, session: string): ProjectionSessionPlanRow | undefined { const row = one<Record<string, unknown>>(store, 'SELECT * FROM session_plans WHERE session = ?', session); return row ? rowToProjectionSessionPlan(row) : undefined; }
export function listProjectionSessionPlanItems(store: EforgePlanStore, session?: string): ProjectionSessionPlanItemRow[] { return all<Record<string, unknown>>(store, `${'SELECT * FROM session_plan_items'}${session ? ' WHERE session = ?' : ''} ORDER BY session, sequence, item_ref`, ...(session ? [session] : [])).map((r) => ({ session: r.session as string, itemRef: r.item_ref as string, itemId: optionalString(r.item_id), role: r.role as string, provenance: r.provenance as string, sourceTaskId: optionalString(r.source_task_id), sourceRecommendationRef: optionalString(r.source_recommendation_ref), promotedAt: optionalString(r.promoted_at), sequence: typeof r.sequence === 'number' ? r.sequence : undefined })); }
export function listProjectionSessionPlanEpics(store: EforgePlanStore, session?: string): Array<{ session: string; epicRef: string; epicId?: string; role: string; provenance: string }> { return all<Record<string, unknown>>(store, `${'SELECT * FROM session_plan_epics'}${session ? ' WHERE session = ?' : ''} ORDER BY session, sequence, epic_ref`, ...(session ? [session] : [])).map((r) => ({ session: r.session as string, epicRef: r.epic_ref as string, epicId: optionalString(r.epic_id), role: r.role as string, provenance: r.provenance as string })); }
